# Tutorial 2: Introduction to NumPy and Pandas

One of the most used packages within our discipline are NumPy and Pandas. This tutorial will focus on teaching you the basics of both of them.

```{admonition} Acknowledgements
This tutorial is heavily based upon the work of [others](https://www.tomasbeuzen.com/python-programming-for-data-science/) 
```



## Important before we start
<hr>
Make sure that you save this file before you continue, else you will lose everything. To do so, go to Bestand/File and click on Een kopie opslaan in Drive/Save a Copy on Drive!

Now, rename the file into Week1_Tutorial2.ipynb. You can do so by clicking on the name in the top of this screen.

<h2>Tutorial Outline<span class="tocSkip"></span></h2>
<hr>
<div class="toc"><ul class="toc-item">
<li><span><a href="#1.-Introduction-to-Python-Packages" data-toc-modified-id="1.-Introduction-to-Python-Packages-1"> Introduction to Python Packages</a></span></li>
<li><span><a href="#2.-Introduction-to-NumPy" data-toc-modified-id="2.-Introduction-to-NumPy-2"> Introduction to NumPy</a></span></li>
<li><span><a href="#3.-NumPy-Arrays" data-toc-modified-id="3.-NumPy-Arrays-23"> NumPy Arrays</a></span></li>
<li><span><a href="#4.-Array-Operations-and-Broadcasting" data-toc-modified-id="4.-Array-Operations-and-Broadcasting-4"> Array Operations and Broadcasting</a></span></li>
<li><span><a href="#5.-Indexing-and-slicing" data-toc-modified-id="5.-Indexing-and-slicing-5"> Indexing and slicing</a></span></li>
<li><span><a href="#6.-More-Useful-NumPy-Functions" data-toc-modified-id="6.-More-Useful-NumPy-Functions-6"> More Useful NumPy Functions</a></span></li>
<li><span><a href="#7.-Introduction-to-Pandas" data-toc-modified-id="7.-Introduction-to-Pandas-7"> Introduction to Pandas</a></span></li>
<li><span><a href="#8.-Pandas-Series" data-toc-modified-id="8.-Pandas-Series-8"> Pandas Series</a></span></li>
<li><span><a href="#9.-Pandas-DataFrames" data-toc-modified-id="9.-Pandas-DataFrames-9"> Pandas DataFrames</a></span></li>
<li><span><a href="#10.-Why-ndarrays-and-Series-and-DataFrames?" data-toc-modified-id="10.-Why-ndarrays-and-Series-and-DataFrames?-10"> Why ndarrays and Series and DataFrames?</a></span></li></ul></div>

##  Learning Objectives
<hr>

**NumPy**
- Use NumPy to create arrays with built-in functions inlcuding `np.array()`, `np.arange()`, `np.linspace()` and `np.full()`, `np.zeros()`, `np.ones()`
- Be able to access values from a NumPy array by numeric indexing, slicing, and boolean indexing
- Perform mathematical operations on and with arrays.
- Explain what broadcasting is and how to use it.
- Reshape arrays by adding/removing/reshaping axes with `.reshape()`, `np.newaxis()`, `.ravel()`, `.flatten()`
- Understand how to use built-in NumPy functions like `np.sum()`, `np.mean()`, `np.log()` as stand alone functions or as methods of numpy arrays (when available)

**Pandas**
- Create Pandas series with `pd.Series()` and Pandas dataframe with `pd.DataFrame()`
- Be able to access values from a Series/DataFrame by numeric indexing, slicing and boolean indexing using notation such as `df[]`, `df.loc[]`, `df.iloc[]`, `df.query[]`
- Perform basic arithmetic operations between two Pandas series and anticipate the result.
- Describe how Pandas assigns dtypes to Series and what the `object` dtype is
- Read a standard .csv file from a local path or url using Pandas `pd.read_csv()`.
- Explain the relationship and differences between `np.ndarray`, `pd.Series` and `pd.DataFrame` objects in Python.

## Performing the exercise
You will do so by performing the scripts in this Python Jupyter notebook. To run any script in the code-boxes below use *crtl+enter*. In some instances, it is necessary to make changes to particular pieces of code in the code-boxes. When this is the case, this will be asked to you before you arrive at the actual script. This is indicated by means of an **Action**. When a script is running this is indicated by the * on the left side of the window.

## 1. Introduction to Python Packages
<hr>

Packages are an essential building block in programming. Without packages, we’d spend lots of time writing code that’s already been written. Imagine having to write code from scratch every time you wanted to parse a file in a particular format. You’d never get anything done! That’s why we always want to use packages.

To understand Python packages, we’ll briefly need to look at scripts and modules. A *script* is something you execute in the shell to accomplish a defined task. To write a script, you’d type your code into your favorite text editor and save it with the .py extension. You can then use the python command in a terminal to execute your script. 

A module on the other hand is a Python program that you import, either in interactive mode or into your other programs. “Module” is really an umbrella term for reusable code.

A Python package usually consists of several modules. Physically, a package is a folder containing modules and maybe other folders that themselves may contain more folders and modules. Conceptually, it’s a namespace. This simply means that a package’s modules are bound together by a package name, by which they may be referenced.

The packages we will use for this tutorial include:

[**OS**](https://docs.python.org/3/library/os.html) is a python module that provides a portable way of using operating system dependent functionality i.e. manipulating paths

[**NumPy**](https://www.labri.fr/perso/nrougier/from-python-to-numpy/) stands for "Numerical Python" and it is the standard Python library used for working with arrays (i.e., vectors & matrices), linear algerba, and other numerical computations. NumPy is written in C, making NumPy arrays faster and more memory efficient than Python lists or arrays

[**Pandas**](https://pypi.org/project/pandas/) is most popular Python library for tabular data structures. You can think of Pandas as an extremely powerful version of Excel (but free and with a lot more features!) 



### Importing a package

We’ll import a package using the import statement:

```python
import <package>
```

## 2. Introduction to NumPy
<hr>

NumPy can be installed using `pip` (in Google Colab pandas and numpy packages are already installed, hence, we will skip this part):

```
!pip install numpy

```


## 3. NumPy Arrays
<hr>

### What are Arrays?

Arrays are "n-dimensional" data structures that can contain all the basic Python data types, e.g., floats, integers, strings etc, but work best with numeric data. NumPy arrays ("ndarrays") are homogenous, which means that items in the array should be of the same type. ndarrays are also compatible with numpy's vast collection of in-built functions!


Usually we import numpy with the alias `np` (to avoid having to type out n-u-m-p-y every time we want to use it):

In [5]:
import numpy as np

A numpy array is sort of like a list:

In [6]:
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [7]:
my_array = np.array([1, 2, 3, 4, 5])
my_array

array([1, 2, 3, 4, 5])

But it has the type `ndarray`:

In [8]:
type(my_array)

numpy.ndarray

Unlike a list, arrays can only hold a single type (usually numbers):

In [9]:
my_list = [1, "hi"]
my_list

[1, 'hi']

In [10]:
my_array = np.array((1, "hi"))
my_array

array(['1', 'hi'], dtype='<U21')

Above: NumPy converted the integer `1` into the string `'1'`!

### Creating arrays

ndarrays are typically created using two main methods:
1. From existing data (usually lists or tuples) using `np.array()`, like we saw above; or,
2. Using built-in functions such as `np.arange()`, `np.linspace()`, `np.zeros()`, etc.

In [11]:
my_list = [1, 2, 3]
np.array(my_list)

array([1, 2, 3])

Just like you can have "multi-dimensional lists" (by nesting lists in lists), you can have multi-dimensional arrays (indicated by double square brackets `[[ ]]`):

In [12]:
list_2d = [[1, 2], [3, 4], [5, 6]]
list_2d

[[1, 2], [3, 4], [5, 6]]

In [13]:
array_2d = np.array(list_2d)
array_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

You'll probably use the built-in numpy array creators quite often. Here are some common ones (hint - don't forget to check the docstrings for help with these functions, if you're in Jupyter, remeber the `shift + tab` shortcut):

In [14]:
np.arange(1, 5)  # from 1 inclusive to 5 exclusive. The counting always starts from 0 and not 1

array([1, 2, 3, 4])

In [15]:
np.arange(0, 11, 2)  # step by 2 from 1 to 11

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.linspace(0, 10, 5)  # 5 equally spaced points between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
np.ones((2, 2))  # an array of ones with size 2 x 2. Always starts with the row then column

array([[1., 1.],
       [1., 1.]])

In [18]:
np.zeros((2, 3))  # an array of zeros with size 2 x 3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.full((3, 3), 3.14)  # an array of the number 3.14 with size 3 x 3

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [20]:
np.full((3, 3, 3), 3.14)  # an array of the number 3.14 with size 3 x 3 x 3

array([[[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]]])

In [21]:
np.random.rand(5, 2)  # random numbers uniformly distributed from 0 to 1 with size 5 x 2

array([[0.47810508, 0.29867106],
       [0.92187501, 0.22836586],
       [0.73352944, 0.95417173],
       [0.56654833, 0.83899703],
       [0.27206196, 0.35851733]])

There are many useful attributes/methods that can be called off numpy arrays:

In [22]:
print(dir(np.ndarray))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [23]:
x = np.random.rand(5, 2)
x

array([[0.46270539, 0.74048964],
       [0.89206036, 0.31950317],
       [0.78438625, 0.84020904],
       [0.5734667 , 0.4545664 ],
       [0.77449337, 0.24267027]])

In [24]:
x.transpose() # converts the rows to columns and vice versa

array([[0.46270539, 0.89206036, 0.78438625, 0.5734667 , 0.77449337],
       [0.74048964, 0.31950317, 0.84020904, 0.4545664 , 0.24267027]])

In [25]:
x.mean()

0.6084550600466357

In [26]:
x.astype(int) # truncates to the nearest whole number

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

### Array Shapes

As you just saw above, arrays can be of any dimension, shape and size you desire. In fact, there are three main array attributes you need to know to work out the characteristics of an array:
- `.ndim`: the number of dimensions of an array
- `.shape`: the number of elements in each dimension (like calling `len()` on each dimension)
- `.size`: the total number of elements in an array (i.e., the product of `.shape`)
*Python f-string is an amazing way to format strings by including a code within the string as shown below*

In [27]:
array_1d = np.ones(3)
print(f"Dimensions: {array_1d.ndim}")
print(f"     Shape: {array_1d.shape}")
print(f"      Size: {array_1d.size}")

Dimensions: 1
     Shape: (3,)
      Size: 3


Let's turn that print action into a function and try out some other arrays:

In [28]:
def print_array(x):
    print(f"Dimensions: {x.ndim}")
    print(f"     Shape: {x.shape}")
    print(f"      Size: {x.size}")
    print("")
    print(x)

In [29]:
array_2d = np.ones((3, 2))
print_array(array_2d)

Dimensions: 2
     Shape: (3, 2)
      Size: 6

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [30]:
array_4d = np.ones((1, 2, 3, 4))
print_array(array_4d)

Dimensions: 4
     Shape: (1, 2, 3, 4)
      Size: 24

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]


After 3 dimensions, printing arrays starts getting pretty messy. As you can see above, the number of square brackets (`[ ]`) in the printed output indicate how many dimensions there are: for example, above, the output starts with 4 square brackets `[[[[` indicative of a 4D array.

### 1-d Arrays

One of the most confusing things about numpy is 1-d arrays (vectors) can have 3 possible shapes!

In [31]:
x = np.ones(5)
print_array(x)

Dimensions: 1
     Shape: (5,)
      Size: 5

[1. 1. 1. 1. 1.]


In [32]:
y = np.ones((1, 5))
print_array(y)

Dimensions: 2
     Shape: (1, 5)
      Size: 5

[[1. 1. 1. 1. 1.]]


In [33]:
z = np.ones((5, 1))
print_array(z)

Dimensions: 2
     Shape: (5, 1)
      Size: 5

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


We can use `np.array_equal()` to determine if two arrays have the same shape and elements:

In [34]:
np.array_equal(x, x)

True

In [35]:
np.array_equal(x, y)

False

In [36]:
np.array_equal(x, z)

False

In [37]:
np.array_equal(y, z)

False

The shape of your 1-d arrays can actually have big implications on your mathematical oeprations!

In [38]:
print(f"x: {x}")
print(f"y: {y}")
print(f"z: {z}")

x: [1. 1. 1. 1. 1.]
y: [[1. 1. 1. 1. 1.]]
z: [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [39]:
x + y  # makes sense

array([[2., 2., 2., 2., 2.]])

In [40]:
y + z  # wait, what?

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

What happened in the cell above is "broadcasting" and we'll discuss it below.

## 4. Array Operations and Broadcasting
<hr>

### Elementwise operations

Elementwise operations refer to operations applied to each element of an array or between the paired elements of two arrays.

In [41]:
x = np.ones(4)
x

array([1., 1., 1., 1.])

In [42]:
y = x + 1
y

array([2., 2., 2., 2.])

In [43]:
x - y # subtraction

array([-1., -1., -1., -1.])

In [44]:
x == y # compares the two arrays

array([False, False, False, False])

In [45]:
x * y # multiplication 

array([2., 2., 2., 2.])

In [46]:
x ** y #exponentiation operator or in simpler terms the power operator

array([1., 1., 1., 1.])

In [47]:
x / y #division

array([0.5, 0.5, 0.5, 0.5])

In [48]:
np.array_equal(x, y)

False

### Broadcasting

ndarrays with different sizes cannot be directly used in arithmetic operations:

In [49]:
a = np.ones((2, 2))
b = np.ones((3, 3))
a + b # this produces an error cause of the different sizes of the arrays

ValueError: ignored

`Broadcasting` describes how NumPy treats arrays with different shapes during arithmetic operations. The idea is to wrangle data so that operations can occur element-wise.

Let's see an example. Say I sell pies on my weekends. I sell 3 types of pies at different prices, and I sold the following number of each pie last weekend. I want to know how much money I made per pie type per day.

<img src="../_static/images/pies.png" class="bg-primary mb-1">

In [50]:
cost = np.array([20, 15, 25])
print("Pie cost:")
print(cost)
sales = np.array([[2, 3, 1], [6, 3, 3], [5, 3, 5]])
print("\nPie sales (#):")
print(sales)

Pie cost:
[20 15 25]

Pie sales (#):
[[2 3 1]
 [6 3 3]
 [5 3 5]]


How can we multiply these two arrays together? We could use a loop:

<img src="../_static/images/pies_loop.png" class="bg-primary mb-1">

In [51]:
total = np.zeros((3, 3))  # initialize an array of 0's
for col in range(sales.shape[1]):
    total[:, col] = sales[:, col] * cost
total

array([[ 40.,  60.,  20.],
       [ 90.,  45.,  45.],
       [125.,  75., 125.]])

Or we could make them the same size, and multiply corresponding elements "elementwise":

<img src="../_static/images/pies_broadcast.png" class="bg-primary mb-1">

In [52]:
cost = np.repeat(cost, 3).reshape((3, 3))
cost

array([[20, 20, 20],
       [15, 15, 15],
       [25, 25, 25]])

In [53]:
cost * sales

array([[ 40,  60,  20],
       [ 90,  45,  45],
       [125,  75, 125]])

Congratulations! You just broadcasted! Broadcasting is just Numpy eessentially doing the `np.repeat()` for you under the hood:

In [54]:
cost = np.array([20, 15, 25]).reshape(3, 1)
print(f" cost shape: {cost.shape}")
sales = np.array([[2, 3, 1], [6, 3, 3], [5, 3, 5]])
print(f"sales shape: {sales.shape}")

 cost shape: (3, 1)
sales shape: (3, 3)


In [55]:
sales * cost

array([[ 40,  60,  20],
       [ 90,  45,  45],
       [125,  75, 125]])

In NumPy the smaller array is “broadcast” across the larger array so that they have compatible shapes:

<img src="../_static/images/broadcasting.png" class="bg-primary mb-1">

Source: [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/) by Jake VanderPlas (2016)

Why should you care about broadcasting? Well, it's cleaner and faster than looping and it also affects the array shapes resulting from arithmetic operations. Below, we can time how long it takes to loop vs broadcast:

In [57]:
cost = np.array([20, 15, 25]).reshape(3, 1)
sales = np.array([[2, 3, 1],
                  [6, 3, 3],
                  [5, 3, 5]])
total = np.zeros((3, 3))

time_loop = %timeit -q -o -r 3 for col in range(sales.shape[1]): total[:, col] = sales[:, col] * np.squeeze(cost)
time_vec = %timeit -q -o -r 3 cost * sales
print(f"Broadcasting is {time_loop.average / time_vec.average:.2f}x faster than looping here.")

Broadcasting is 5.45x faster than looping here.


Of course, not all arrays are compatible! NumPy compares arrays element-wise. It starts with the trailing dimensions, and works its way forward. Dimensions are compatible if:
- **they are equal**, or
- **one of them is 1**.

Use the code below to test out array compatibitlity:

In [58]:
a = np.ones((3, 2))
b = np.ones((3, 2, 1))
print(f"The shape of a is: {a.shape}")
print(f"The shape of b is: {b.shape}")
print("")
try:
    print(f"The shape of a + b is: {(a + b).shape}")
except:
    print(f"ERROR: arrays are NOT broadcast compatible!")

The shape of a is: (3, 2)
The shape of b is: (3, 2, 1)

ERROR: arrays are NOT broadcast compatible!


### Reshaping Arrays

There are 3 key reshaping methods I want you to know about for reshaping numpy arrays:
- `.rehshape()`
- `np.newaxis`
- `.ravel()`/`.flatten()`

In [59]:
x = np.full((4, 3), 3.14)
x

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

You'll reshape arrays farily often and the `.reshape()` method is pretty intuitive:

In [60]:
x.reshape(6, 2)

array([[3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14]])

In [61]:
x.reshape(2, -1)  # using -1 will calculate the dimension for you (if possible)

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

In [62]:
a = np.ones(3)
print_array(a)
b = np.ones((3, 2))
print_array(b)

Dimensions: 1
     Shape: (3,)
      Size: 3

[1. 1. 1.]
Dimensions: 2
     Shape: (3, 2)
      Size: 6

[[1. 1.]
 [1. 1.]
 [1. 1.]]


If I want to add these two arrays I won't be able to because their dimensions are not compatible:

In [63]:
a + b

ValueError: ignored

Sometimes you'll want to add dimensions to an array for broadcasting purposes like this. We can do that with `np.newaxis` (note that `None` is an alias for `np.newaxis`). We can add a dimension to `a` to make the arrays compatible:

In [64]:
print_array(a[:, np.newaxis])  # same as a[:, None]

Dimensions: 2
     Shape: (3, 1)
      Size: 3

[[1.]
 [1.]
 [1.]]


In [65]:
a[:, np.newaxis] + b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

Finally, sometimes you'll want to "flatten" arrays to a single dimension using `.ravel()` or `.flatten()`. `.flatten()` used to return a copy and `.ravel()` a view/reference but now they both return a copy so I can't think of an important reason to use one over the other 🤷‍♂️

In [66]:
x

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [67]:
print_array(x.flatten())

Dimensions: 1
     Shape: (12,)
      Size: 12

[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]


In [68]:
print_array(x.ravel())

Dimensions: 1
     Shape: (12,)
      Size: 12

[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]


## 5. Indexing and slicing
<hr>

Concepts of indexing should be pretty familiar by now. Indexing arrays is similar to indexing lists but there are just more dimensions.

### Numeric Indexing

In [69]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
x[3]

3

In [71]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
x[:4]

array([0, 1, 2, 3])

In [73]:
x[2:5]

array([2, 3, 4])

In [74]:
x[2:3]

array([2])

In [75]:
x[-1]

9

In [76]:
x[-2]

8

In [77]:
x[5:0:-1] # the -1 means going backwards

array([5, 4, 3, 2, 1])

For 2D arrays:

In [78]:
x = np.random.randint(10, size=(4, 6))
x

array([[0, 1, 4, 4, 9, 3],
       [3, 5, 6, 7, 1, 8],
       [9, 3, 5, 3, 0, 3],
       [0, 8, 1, 5, 4, 8]])

In [79]:
x[3, 4]  # do this

4

In [80]:
x[3][4]  # i do not like this as much

4

In [81]:
x[3]

array([0, 8, 1, 5, 4, 8])

In [82]:
len(x)  # generally, just confusing

4

In [83]:
x.shape

(4, 6)

In [84]:
x[:, 2]  # column number 2

array([4, 6, 5, 1])

In [85]:
x[2:, :3]

array([[9, 3, 5],
       [0, 8, 1]])

In [86]:
x.T

array([[0, 3, 9, 0],
       [1, 5, 3, 8],
       [4, 6, 5, 1],
       [4, 7, 3, 5],
       [9, 1, 0, 4],
       [3, 8, 3, 8]])

In [87]:
x

array([[0, 1, 4, 4, 9, 3],
       [3, 5, 6, 7, 1, 8],
       [9, 3, 5, 3, 0, 3],
       [0, 8, 1, 5, 4, 8]])

In [88]:
x[1, 1] = 555555
x

array([[     0,      1,      4,      4,      9,      3],
       [     3, 555555,      6,      7,      1,      8],
       [     9,      3,      5,      3,      0,      3],
       [     0,      8,      1,      5,      4,      8]])

In [89]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [90]:
z[0] = 5
z

array([5., 0., 0., 0., 0.])

### Boolean Indexing

In [91]:
x = np.random.rand(10)
x

array([0.35009527, 0.2595618 , 0.11112358, 0.34119462, 0.40338885,
       0.24519029, 0.44319778, 0.95884403, 0.28980175, 0.94607844])

In [92]:
x + 1

array([1.35009527, 1.2595618 , 1.11112358, 1.34119462, 1.40338885,
       1.24519029, 1.44319778, 1.95884403, 1.28980175, 1.94607844])

In [93]:
x_thresh = x > 0.5
x_thresh

array([False, False, False, False, False, False, False,  True, False,
        True])

In [94]:
x[x_thresh] = 0.5  # set all elements  > 0.5 to be equal to 0.5
x

array([0.35009527, 0.2595618 , 0.11112358, 0.34119462, 0.40338885,
       0.24519029, 0.44319778, 0.5       , 0.28980175, 0.5       ])

In [95]:
x = np.random.rand(10)
x

array([0.259092  , 0.76143111, 0.95080491, 0.84569269, 0.93307087,
       0.09290223, 0.38738502, 0.82043566, 0.03311822, 0.68690357])

In [96]:
x[x > 0.5] = 0.5
x

array([0.259092  , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.09290223, 0.38738502, 0.5       , 0.03311822, 0.5       ])

## 6. More Useful NumPy Functions

Numpy has many built-in functions for mathematical operations, really it has almost every numerical operation you might want to do in its library. I'm not going to explore the whole library here, but as an example of some of the available functions, consider working out the hypotenuse of a triangle that with sides 3m and 4m:

In [97]:
sides = np.array([3, 4])

There are several ways we could solve this problem. We could directly use Pythagoras's Theorem:

$$c = \sqrt{a^2+b^2}$$

In [98]:
np.sqrt(np.sum([np.power(sides[0], 2), np.power(sides[1], 2)]))

5.0

We can leverage the fact that we're dealing with a numpy array and apply a "vectorized" operation (more on that in a bit) to the whole vector at one time:

In [99]:
(sides ** 2).sum() ** 0.5

5.0

Or we can simply use a numpy built-in function (if it exists):

In [100]:
np.linalg.norm(sides)  # you'll learn more about norms in 573

5.0

In [101]:
np.hypot(*sides)

5.0

### Vectorization

Broadly speaking, "vectorization" in NumPy refers to the use of optmized C code to perform an operation. Long-story-short, because numpy arrays are homogenous (contain the same dtype), we don't need to check that we can perform an operation on elements of a sequence before we do the operation which results in a huge speed-up. You can kind of think of this concept as NumPy being able to perform an operation on the whole array at the same time rather than one-by-one (this is not actually the case, a super-efficient C loop is still running under the hood, but that's an irrelevant detail). You can read more about vectorization [here](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/VectorizedOperations.html) but all you need to know is that most operations in NumPy are vectorized, so just try to do things at an "array-level" rather than an "element-level", e.g.:

In [102]:
# DONT DO THIS
array = np.array(range(5))
for i, element in enumerate(array):
    array[i] = element ** 2
array

array([ 0,  1,  4,  9, 16])

In [103]:
# DO THIS
array = np.array(range(5))
array **= 2 

Let's do a quick timing experiment:

In [104]:
# loop method
array = np.array(range(5))
time_loop = %timeit -q -o -r 3 for i, element in enumerate(array): array[i] = element ** 2
# vectorized method
array = np.array(range(5))
time_vec = %timeit -q -o -r 3 array ** 2
print(f"Vectorized operation is {time_loop.average / time_vec.average:.2f}x faster than looping here.")

Vectorized operation is 1.51x faster than looping here.


## 7. Introduction to Pandas
<hr>

Pandas can be installed using `pip`:

```
!pip install pandas
```

We usually import pandas with the alias `pd`. You'll see these two imports at the top of most data science workflows:

In [105]:
import pandas as pd

## 8. Pandas Series
<hr>

### What are Series?

A Series is like a NumPy array but with labels. They are strictly 1-dimensional and can contain any data type (integers, strings, floats, objects, etc), including a mix of them. Series can be created from a scalar, a list, ndarray or dictionary using `pd.Series()` (**note the captial "S"**). Here are some example series:

### Creating Series

By default, series are labelled with indices starting from 0. For example:

In [106]:
pd.Series(data = [-5, 1.3, 21, 6, 3])

0    -5.0
1     1.3
2    21.0
3     6.0
4     3.0
dtype: float64

But you can add a custom index:

In [107]:
pd.Series(data = [-5, 1.3, 21, 6, 3],
          index = ['a', 'b', 'c', 'd', 'e'])

a    -5.0
b     1.3
c    21.0
d     6.0
e     3.0
dtype: float64

You can create a Series from a dictionary:

In [108]:
pd.Series(data = {'a': 10, 'b': 20, 'c': 30})

a    10
b    20
c    30
dtype: int64

Or from an ndarray:

In [109]:
pd.Series(data = np.random.randn(3))

0    0.743589
1    0.377479
2    0.605400
dtype: float64

Or even a scalar:

In [110]:
pd.Series(3.141)

0    3.141
dtype: float64

In [111]:
pd.Series(data=3.141, index=['a', 'b', 'c'])

a    3.141
b    3.141
c    3.141
dtype: float64

### Series Characteristics

Series can be given a `name` attribute. I almost never use this but it might come up sometimes:

In [112]:
s = pd.Series(data = np.random.randn(5), name='random_series')
s

0   -0.340770
1    0.158654
2    0.155531
3   -0.064391
4    0.100861
Name: random_series, dtype: float64

In [113]:
s.name

'random_series'

In [114]:
s.rename("another_name")

0   -0.340770
1    0.158654
2    0.155531
3   -0.064391
4    0.100861
Name: another_name, dtype: float64

You can access the index labels of your series using the `.index` attribute:

In [115]:
s.index

RangeIndex(start=0, stop=5, step=1)

You can access the underlying data array using `.to_numpy()`:

In [116]:
s.to_numpy()

array([-0.34077002,  0.15865382,  0.15553096, -0.06439118,  0.10086057])

In [117]:
pd.Series([[1, 2, 3], "b", 1]).to_numpy()

array([list([1, 2, 3]), 'b', 1], dtype=object)

### Indexing and Slicing Series

Series are very much like ndarrays (in fact, series can be passed to most NumPy functions!). They can be indexed using square brackets `[ ]` and sliced using colon `:` notation:

In [118]:
s = pd.Series(data = range(5),
              index = ['A', 'B', 'C', 'D', 'E'])
s

A    0
B    1
C    2
D    3
E    4
dtype: int64

In [119]:
s[0]

0

In [120]:
s[[1, 2, 3]]

B    1
C    2
D    3
dtype: int64

In [121]:
s[0:3]

A    0
B    1
C    2
dtype: int64

Note above how array-based indexing and slicing also returns the series index.

Series are also like dictionaries, in that we can access values using index labels:

In [122]:
s["A"]

0

In [123]:
s[["B", "D", "C"]]

B    1
D    3
C    2
dtype: int64

In [124]:
s["A":"C"]

A    0
B    1
C    2
dtype: int64

In [125]:
"A" in s

True

In [126]:
"Z" in s

False

Series do allow for non-unique indexing, but **be careful** because indexing operations won't return unique values:

In [127]:
x = pd.Series(data = range(5),
              index = ["A", "A", "A", "B", "C"])
x

A    0
A    1
A    2
B    3
C    4
dtype: int64

In [128]:
x["A"]

A    0
A    1
A    2
dtype: int64

Finally, we can also do boolean indexing with series:

In [129]:
s[s >= 1]

B    1
C    2
D    3
E    4
dtype: int64

In [130]:
s[s > s.mean()]

D    3
E    4
dtype: int64

In [131]:
(s != 1)

A     True
B    False
C     True
D     True
E     True
dtype: bool

### Series Operations

Unlike ndarrays operations between Series (+, -, /, \*) align values based on their **LABELS** (not their position in the structure). The resulting index will be the __*sorted union*__ of the two indexes. This gives you the flexibility to run operations on series regardless of their labels.

In [132]:
s1 = pd.Series(data = range(4),
               index = ["A", "B", "C", "D"])
s1

A    0
B    1
C    2
D    3
dtype: int64

In [133]:
s2 = pd.Series(data = range(10, 14),
               index = ["B", "C", "D", "E"])
s2

B    10
C    11
D    12
E    13
dtype: int64

In [134]:
s1 + s2

A     NaN
B    11.0
C    13.0
D    15.0
E     NaN
dtype: float64

As you can see above, indices that match will be operated on. Indices that don't match will appear in the product but with `NaN` values:

We can also perform standard operations on a series, like multiplying or squaring. NumPy also accepts series as an argument to most functions because series are built off numpy arrays (more on that later):

In [139]:
s1 ** 2

A    0
B    1
C    4
D    9
dtype: int64

In [140]:
np.exp(s1)

A     1.000000
B     2.718282
C     7.389056
D    20.085537
dtype: float64

Finally, just like arrays, series have many built-in methods for various operations. You can find them all by running `help(pd.Series)`:

In [141]:
print([_ for _ in dir(pd.Series) if not _.startswith("_")])  # print all common methods

['T', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'append', 'apply', 'argmax', 'argmin', 'argsort', 'array', 'asfreq', 'asof', 'astype', 'at', 'at_time', 'attrs', 'autocorr', 'axes', 'backfill', 'between', 'between_time', 'bfill', 'bool', 'cat', 'clip', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'divmod', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dt', 'dtype', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'ewm', 'expanding', 'explode', 'factorize', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'ge', 'get', 'groupby', 'gt', 'hasnans', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'interpolate', 'is_monotonic', 'is_monotonic_decreasing', 'is_monotonic_increasing', 'is_unique', 'isin', 'isna', 'isnull', 'item', 'items', 'iteritems', 'keys', 'ku

In [142]:
s1

A    0
B    1
C    2
D    3
dtype: int64

In [143]:
s1.mean()

1.5

In [144]:
s1.sum()

6

In [145]:
s1.astype(float)

A    0.0
B    1.0
C    2.0
D    3.0
dtype: float64

**"Chaining"** operations together is also common with pandas:

In [146]:
s1.add(3.141).astype(int).pow(2).mean()

21.5

### Data Types

Series can hold all the data types (`dtypes`) you're used to, e.g., `int`, `float`, `bool`, etc. There are a few other special data types too (`object`, `DateTime` and `Categorical`) which we'll talk about in this and later chapters. You can always read more about pandas dtypes [in the documentation too](https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html#dtypes). For example, here's a series of `dtype` int64:

In [147]:
x = pd.Series(range(5))
x.dtype

dtype('int64')

The dtype "`object`" is used for series of strings or mixed data. Pandas is [currently experimenting](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.StringDtype.html#pandas.StringDtype) with a dedicated string dtype `StringDtype`, but it is still in testing.

In [148]:
x = pd.Series(['A', 'B'])
x

0    A
1    B
dtype: object

In [149]:
x = pd.Series(['A', 1, ["I", "AM", "A", "LIST"]])
x

0                   A
1                   1
2    [I, AM, A, LIST]
dtype: object

While flexible, it is recommended to avoid the use of `object` dtypes because of higher memory requirements. Essentially, in an `object` dtype series, every single element stores information about its individual dtype. We can inspect the dtypes of all the elements in a mixed series in several ways, below I'll use the `map` method:

In [150]:
x.map(type)

0     <class 'str'>
1     <class 'int'>
2    <class 'list'>
dtype: object

We can see that each object in our series has a different dtype. This comes at a cost. Compare the [memory usage](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.memory_usage.html) of the series below:

In [151]:
x1 = pd.Series([1, 2, 3])
print(f"x1 dtype: {x1.dtype}")
print(f"x1 memory usage: {x1.memory_usage(deep=True)} bytes")
print("")
x2 = pd.Series([1, 2, "3"])
print(f"x2 dtype: {x2.dtype}")
print(f"x2 memory usage: {x2.memory_usage(deep=True)} bytes")
print("")
x3 = pd.Series([1, 2, "3"]).astype('int8')  # coerce the object series to int8
print(f"x3 dtype: {x3.dtype}")
print(f"x3 memory usage: {x3.memory_usage(deep=True)} bytes")

x1 dtype: int64
x1 memory usage: 152 bytes

x2 dtype: object
x2 memory usage: 258 bytes

x3 dtype: int8
x3 memory usage: 131 bytes


In summary, try to use uniform dtypes where possible - they are more memory efficient!

One more gotcha, `NaN` (frequently used to represent missing values in data) is a float:

In [152]:
type(np.NaN)

float

This can be problematic if you have a series of integers and one missing value, because Pandas will cast the whole series to a float:

In [153]:
pd.Series([1, 2, 3, np.NaN])

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

Only recently, Pandas has implemented a "[nullable integer dtype](https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html)", which can handle `NaN` in an integer series without affecting the `dtype`. Note the captial "I" in the type below, differentiating it from numpy's `int64` dtype:

In [154]:
pd.Series([1, 2, 3, np.NaN]).astype('Int64')

0       1
1       2
2       3
3    <NA>
dtype: Int64

This is not the default in Pandas yet and functionality of this new feature is still subject to change.

## 9. Pandas DataFrames
<hr>

### What are DataFrames?

Pandas DataFrames are you're new best friend. They are like the Excel spreadsheets you may be used to. DataFrames are really just Series stuck together! Think of a DataFrame as a dictionary of series, with the "keys" being the column labels and the "values" being the series data:



### Creating DataFrames

Dataframes can be created using `pd.DataFrame()` (note the capital "D" and "F"). Like series, index and column labels of dataframes are labelled starting from 0 by default:

In [155]:
pd.DataFrame([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

We can use the `index` and `columns` arguments to give them labels:

In [156]:
pd.DataFrame([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]],
             index = ["R1", "R2", "R3"],
             columns = ["C1", "C2", "C3"])

C1  C2  C3
R1   1   2   3
R2   4   5   6
R3   7   8   9

There are so many ways to create dataframes. I most often create them from dictionaries or ndarrays:

In [157]:
pd.DataFrame({"C1": [1, 2, 3],
              "C2": ['A', 'B', 'C']},
             index=["R1", "R2", "R3"])

C1 C2
R1   1  A
R2   2  B
R3   3  C

In [158]:
pd.DataFrame(np.random.randn(5, 5),
             index=[f"row_{_}" for _ in range(1, 6)],
             columns=[f"col_{_}" for _ in range(1, 6)])

col_1     col_2     col_3     col_4     col_5
row_1  1.475944  0.636854 -1.575953  0.980301 -0.459563
row_2 -0.504227 -0.954323  0.465814  1.063984  2.745003
row_3 -1.246350 -1.113726 -2.734928 -2.185122 -1.162823
row_4 -0.882772 -0.024637 -2.258099  0.924045 -0.544247
row_5  0.962939  1.032386  1.093798 -1.115438  1.005228

In [159]:
pd.DataFrame(np.array([['Tom', 7], ['Mike', 15], ['Tiffany', 3]]))

0   1
0      Tom   7
1     Mike  15
2  Tiffany   3

Here's a table of the main ways you can create dataframes (see the [Pandas documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/dsintro.html#dataframe) for more):

|Create DataFrame from|Code|
|---|---|
|Lists of lists|`pd.DataFrame([['Tom', 7], ['Mike', 15], ['Tiffany', 3]])`|
|ndarray|`pd.DataFrame(np.array([['Tom', 7], ['Mike', 15], ['Tiffany', 3]]))`|
|Dictionary|`pd.DataFrame({"Name": ['Tom', 'Mike', 'Tiffany'], "Number": [7, 15, 3]})`|
|List of tuples|`pd.DataFrame(zip(['Tom', 'Mike', 'Tiffany'], [7, 15, 3]))`|
|Series|`pd.DataFrame({"Name": pd.Series(['Tom', 'Mike', 'Tiffany']), "Number": pd.Series([7, 15, 3])})`|


### Indexing and Slicing DataFrames

There are several main ways to select data from a DataFrame:
1. `[]`
2. `.loc[]`
3. `.iloc[]`
4. Boolean indexing
5. `.query()`

In [160]:
df = pd.DataFrame({"Name": ["Tom", "Mike", "Tiffany"],
                   "Language": ["Python", "Python", "R"],
                   "Courses": [5, 4, 7]})
df

Name Language  Courses
0      Tom   Python        5
1     Mike   Python        4
2  Tiffany        R        7

#### Indexing with `[]`
Select columns by single labels, lists of labels, or slices:

In [161]:
df['Name']  # returns a series

0        Tom
1       Mike
2    Tiffany
Name: Name, dtype: object

In [162]:
df[['Name']]  # returns a dataframe!

Name
0      Tom
1     Mike
2  Tiffany

In [163]:
df[['Name', 'Language']]

Name Language
0      Tom   Python
1     Mike   Python
2  Tiffany        R

You can only index rows by using slices, not single values (but not recommended, see preferred methods below).

In [164]:
df[0] # doesn't work

KeyError: ignored

In [165]:
df[0:1] # does work

Name Language  Courses
0  Tom   Python        5

In [166]:
df[1:] # does work

Name Language  Courses
1     Mike   Python        4
2  Tiffany        R        7

#### Indexing with `.loc` and `.iloc`
Pandas created the methods `.loc[]` and `.iloc[]` as more flexible alternatives for accessing data from a dataframe. Use `df.iloc[]` for indexing with integers and `df.loc[]` for indexing with labels. These are typically the [recommended methods of indexing](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated) in Pandas.

In [167]:
df

Name Language  Courses
0      Tom   Python        5
1     Mike   Python        4
2  Tiffany        R        7

First we'll try out `.iloc` which accepts *integers* as references to rows/columns:

In [168]:
df.iloc[0]  # returns a series

Name           Tom
Language    Python
Courses          5
Name: 0, dtype: object

In [169]:
df.iloc[0:2]  # slicing returns a dataframe

Name Language  Courses
0   Tom   Python        5
1  Mike   Python        4

In [170]:
df.iloc[2, 1]  # returns the indexed object

'R'

In [171]:
df.iloc[[0, 1], [1, 2]]  # returns a dataframe

Language  Courses
0   Python        5
1   Python        4

Now let's look at `.loc` which accepts *labels* as references to rows/columns:

In [172]:
df.loc[:, 'Name']

0        Tom
1       Mike
2    Tiffany
Name: Name, dtype: object

In [173]:
df.loc[:, 'Name':'Language']

Name Language
0      Tom   Python
1     Mike   Python
2  Tiffany        R

In [174]:
df.loc[[0, 2], ['Language']]

Language
0   Python
2        R

Sometimes we want to use a mix of integers and labels to reference data in a dataframe. The easiest way to do this is to use `.loc[]` with a label then use an integer in combinations with `.index` or `.columns`:

In [175]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [176]:
df.columns

Index(['Name', 'Language', 'Courses'], dtype='object')

In [177]:
df.loc[df.index[0], 'Courses']  # I want to reference the first row and the column named "Courses"

5

In [178]:
df.loc[2, df.columns[1]]  # I want to reference row "2" and the second column

'R'

#### Boolean indexing
Just like with series, we can select data based on boolean masks:

In [179]:
df

Name Language  Courses
0      Tom   Python        5
1     Mike   Python        4
2  Tiffany        R        7

In [180]:
df[df['Courses'] > 5]

Name Language  Courses
2  Tiffany        R        7

In [181]:
df[df['Name'] == "Tom"]

Name Language  Courses
0  Tom   Python        5

#### Indexing with `.query()`
Boolean masks work fine, but I prefer to use the `.query()` method for selecting data. `df.query()` is a powerful tool for filtering data. It has an odd syntax, one of the strangest I've seen in Python, it is more like SQL - `df.query()` accepts a string expression to evaluate and it "knows" the names of the columns in your dataframe.

In [182]:
df.query("Courses > 4 & Language == 'Python'")

Name Language  Courses
0  Tom   Python        5

Note the use of single quotes AND double quotes above, lucky we have both in Python! Compare this to the equivalent boolean indexing operation and you can see that `.query()` is much more readable, especially as the query gets bigger!

In [183]:
df[(df['Courses'] > 4) & (df['Language'] == 'Python')]

Name Language  Courses
0  Tom   Python        5

Query also allows you to reference variable in the current workspace using the `@` symbol:

In [184]:
course_threshold = 4
df.query("Courses > @course_threshold")

Name Language  Courses
0      Tom   Python        5
2  Tiffany        R        7

#### Indexing cheatsheet

|Method|Syntax|Output|
|---|---|---|
|Select column|`df[col_label]`|Series|
|Select row slice|`df[row_1_int:row_2_int]`|DataFrame|
|Select row/column by label|`df.loc[row_label(s), col_label(s)]`|Object for single selection, Series for one row/column, otherwise DataFrame|
|Select row/column by integer|`df.iloc[row_int(s), col_int(s)]`|Object for single selection, Series for one row/column, otherwise DataFrame|
|Select by row integer & column label|`df.loc[df.index[row_int], col_label]`|Object for single selection, Series for one row/column, otherwise DataFrame|
|Select by row label & column integer|`df.loc[row_label, df.columns[col_int]]`|Object for single selection, Series for one row/column, otherwise DataFrame|
|Select by boolean|`df[bool_vec]`|Object for single selection, Series for one row/column, otherwise DataFrame|
|Select by boolean expression|`df.query("expression")`|Object for single selection, Series for one row/column, otherwise DataFrame|

### Reading/Writing Data From External Sources

#### .csv files

A lot of the time you will be loading .csv files for use in pandas. You can use the `pd.read_csv()` function for this. In the following chapters we'll use a real dataset of my cycling commutes to the University of British Columbia. There are so many arguments that can be used to help read in your .csv file in an efficient and appropriate manner, feel free to check them out now (by using `shift + tab` in Jupyter, or typing `help(pd.read_csv)`).

In [189]:
path = os.path.join(data_path,'weather.csv')
df = pd.read_csv(path, index_col=0, parse_dates=True)
df

Date.Full  Date.Month  Date.Week of  Date.Year  \
Data.Precipitation                                                    
0.00                2016-01-03           1             3       2016   
0.00                2016-01-03           1             3       2016   
0.16                2016-01-03           1             3       2016   
0.00                2016-01-03           1             3       2016   
0.01                2016-01-03           1             3       2016   
...                        ...         ...           ...        ...   
0.08                2017-01-01           1             1       2017   
0.00                2017-01-01           1             1       2017   
0.00                2017-01-01           1             1       2017   
0.06                2017-01-01           1             1       2017   
0.10                2017-01-01           1             1       2017   

                   Station.City Station.Code Station.Location Station.State  \
Data.Precipitation                                                            
0.00                 Birmingham          BHM   Birmingham, AL       Alabama   
0.00                 Huntsville          HSV   Huntsville, AL       Alabama   
0.16                     Mobile          MOB       Mobile, AL       Alabama   
0.00                 Montgomery          MGM   Montgomery, AL       Alabama   
0.01                  Anchorage          ANC    Anchorage, AK        Alaska   
...                         ...          ...              ...           ...   
0.08                     Casper          CPR       Casper, WY       Wyoming   
0.00                   Cheyenne          CYS     Cheyenne, WY       Wyoming   
0.00                     Lander          LND       Lander, WY       Wyoming   
0.06                    Rawlins          RWL      Rawlins, WY       Wyoming   
0.10                   Sheridan          SHR     Sheridan, WY       Wyoming   

                    Data.Temperature.Avg Temp  Data.Temperature.Max Temp  \
Data.Precipitation                                                         
0.00                                       39                         46   
0.00                                       39                         47   
0.16                                       46                         51   
0.00                                       45                         52   
0.01                                       34                         38   
...                                       ...                        ...   
0.08                                       23                         32   
0.00                                       32                         42   
0.00                                       17                         29   
0.06                                       23                         31   
0.10                                       21                         34   

                    Data.Temperature.Min Temp  Data.Wind.Direction  \
Data.Precipitation                                                   
0.00                                       32                   33   
0.00                                       31                   32   
0.16                                       41                   35   
0.00                                       38                   32   
0.01                                       29                   19   
...                                       ...                  ...   
0.08                                       15                   23   
0.00                                       21                   26   
0.00                                        4                   26   
0.06                                       13                   24   
0.10                                        8                   23   

                    Data.Wind.Speed  
Data.Precipitation                   
0.00                           4.33  
0.00                           3.86  
0.16             

You can print a dataframe to .csv using `df.to_csv()`. Be sure to check out all of the possible arguments to write your dataframe exactly how you want it.

#### url

Pandas also facilitates reading directly from a url - `pd.read_csv()` accepts urls as input:

In [190]:
url = 'https://raw.githubusercontent.com/TomasBeuzen/toy-datasets/master/wine_1.csv'
pd.read_csv(url)

Bottle         Grape     Origin  Alcohol    pH Colour   Aroma
0       1    Chardonnay  Australia    14.23  3.51  White  Floral
1       2  Pinot Grigio      Italy    13.20  3.30  White  Fruity
2       3   Pinot Blanc     France    13.16  3.16  White  Citrus
3       4        Shiraz      Chile    14.91  3.39    Red   Berry
4       5        Malbec  Argentina    13.83  3.28    Red  Fruity

#### Other
Pandas can read data from all sorts of other file types including HTML, JSON, Excel, Parquet, Feather, etc. There are generally dedicated functions for reading these file types, see the [Pandas documentation here](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-tools-text-csv-hdf5).

### Common DataFrame Operations

DataFrames have built-in functions for performing most common operations, e.g., `.min()`, `idxmin()`, `sort_values()`, etc. They're all documented in the [Pandas documentation here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html) but I'll demonstrate a few below:

In [193]:
df = pd.read_csv(path)
df.head()

Data.Precipitation   Date.Full  Date.Month  Date.Week of  Date.Year  \
0                0.00  2016-01-03           1             3       2016   
1                0.00  2016-01-03           1             3       2016   
2                0.16  2016-01-03           1             3       2016   
3                0.00  2016-01-03           1             3       2016   
4                0.01  2016-01-03           1             3       2016   

  Station.City Station.Code Station.Location Station.State  \
0   Birmingham          BHM   Birmingham, AL       Alabama   
1   Huntsville          HSV   Huntsville, AL       Alabama   
2       Mobile          MOB       Mobile, AL       Alabama   
3   Montgomery          MGM   Montgomery, AL       Alabama   
4    Anchorage          ANC    Anchorage, AK        Alaska   

   Data.Temperature.Avg Temp  Data.Temperature.Max Temp  \
0                         39                         46   
1                         39                         47   
2                         46                         51   
3                         45                         52   
4                         34                         38   

   Data.Temperature.Min Temp  Data.Wind.Direction  Data.Wind.Speed  
0                         32                   33             4.33  
1                         31                   32             3.86  
2                         41                   35             9.73  
3                         38                   32             6.86  
4                         29                   19             7.80

In [194]:
df.columns # to view all the columns within the dataframe

Index(['Data.Precipitation', 'Date.Full', 'Date.Month', 'Date.Week of',
       'Date.Year', 'Station.City', 'Station.Code', 'Station.Location',
       'Station.State', 'Data.Temperature.Avg Temp',
       'Data.Temperature.Max Temp', 'Data.Temperature.Min Temp',
       'Data.Wind.Direction', 'Data.Wind.Speed'],
      dtype='object')

In [195]:
df.min()

Data.Precipitation                    0.0
Date.Full                      2016-01-03
Date.Month                              1
Date.Week of                            1
Date.Year                            2016
Station.City                     Aberdeen
Station.Code                          ABE
Station.Location             Aberdeen, SD
Station.State                     Alabama
Data.Temperature.Avg Temp             -27
Data.Temperature.Max Temp             -19
Data.Temperature.Min Temp             -35
Data.Wind.Direction                     0
Data.Wind.Speed                       0.0
dtype: object

In [196]:
df['Data.Temperature.Avg Temp'].min()

-27

In [197]:
df['Data.Temperature.Avg Temp'].idxmin() # position index of the min temperature

15165

In [198]:
df.iloc[20]

Data.Precipitation                    0.1
Date.Full                      2016-01-03
Date.Month                              1
Date.Week of                            3
Date.Year                            2016
Station.City                     Kotzebue
Station.Code                          OTZ
Station.Location             Kotzebue, AK
Station.State                      Alaska
Data.Temperature.Avg Temp              27
Data.Temperature.Max Temp              33
Data.Temperature.Min Temp              20
Data.Wind.Direction                    11
Data.Wind.Speed                     11.76
Name: 20, dtype: object

In [199]:
df.sum()

Data.Precipitation                                                     9695.71
Date.Full                    2016-01-032016-01-032016-01-032016-01-032016-0...
Date.Month                                                              106203
Date.Week of                                                            262032
Date.Year                                                             33754205
Station.City                 BirminghamHuntsvilleMobileMontgomeryAnchorageA...
Station.Code                 BHMHSVMOBMGMANCANNBETBTTCDBCDVBIGFAIGKNHOMILIJ...
Station.Location             Birmingham, ALHuntsville, ALMobile, ALMontgome...
Station.State                AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
Data.Temperature.Avg Temp                                               939100
Data.Temperature.Max Temp                                              1105748
Data.Temperature.Min Temp                                               764196
Data.Wind.Direction                                 

Some methods like `.mean()` will only operate on numeric columns:

In [200]:
df.mean()

<ipython-input-200-c61f0c8f89b5>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()


Data.Precipitation              0.579090
Date.Month                      6.343128
Date.Week of                   15.650242
Date.Year                    2016.018933
Data.Temperature.Avg Temp      56.089112
Data.Temperature.Max Temp      66.042406
Data.Temperature.Min Temp      45.642716
Data.Wind.Direction            18.791316
Data.Wind.Speed                 6.329820
dtype: float64

Some methods require arguments to be specified, like `.sort_values()`:

In [201]:
df.sort_values(by='Data.Temperature.Max Temp')

Data.Precipitation   Date.Full  Date.Month  Date.Week of  Date.Year  \
15165                0.01  2016-12-04          12             4       2016   
15486                0.00  2016-12-11          12            11       2016   
15816                0.00  2016-12-18          12            18       2016   
15487                0.47  2016-12-11          12            11       2016   
15180                0.00  2016-12-04          12             4       2016   
...                   ...         ...         ...           ...        ...   
7932                 0.00  2016-06-26           6            26       2016   
8081                 0.00  2016-06-26           6            26       2016   
6986                 0.00  2016-06-05           6             5       2016   
9513                 0.00  2016-07-31           7            31       2016   
9653                 0.03  2016-07-31           7            31       2016   

      Station.City Station.Code Station.Location Station.State  \
15165      Bettles          BTT      Bettles, AK        Alaska   
15486    Fairbanks          FAI    Fairbanks, AK        Alaska   
15816     Northway          ORT     Northway, AK        Alaska   
15487      Gulkana          GKN      Gulkana, AK        Alaska   
15180     Mc Grath          MCG     Mc Grath, AK        Alaska   
...            ...          ...              ...           ...   
7932       Phoenix          PHX      Phoenix, AZ       Arizona   
8081     Las Vegas          LAS    Las Vegas, NV        Nevada   
6986       Phoenix          PHX      Phoenix, AZ       Arizona   
9513    China Lake          NID   China Lake, CA    California   
9653     Las Vegas          LAS    Las Vegas, NV        Nevada   

       Data.Temperature.Avg Temp  Data.Temperature.Max Temp  \
15165                        -27                        -19   
15486                        -21                        -16   
15816                        -21                        -15   
15487                        -20                        -11   
15180                        -19                        -11   
...                          ...                        ...   
7932                          99                        110   
8081                          98                        110   
6986                          95                        110   
9513                          93                        111   
9653                         100                        111   

       Data.Temperature.Min Temp  Data.Wind.Direction  Data.Wind.Speed  
15165                        -35                   17             1.32  
15486                        -27                    3             2.57  
15816                        -28                   16             0.20  
15487                        -28                   33             0.85  
15180                        -26                   29             2.87  
...                          ...                  ...              ...  
7932                          88                   24             3.10  
8081                          85                   17             4.78  
6986                          79                   26             4.08  
9513                          75                   19             5.27  
9653                          88                   15             3.58  

[16743 rows x 14 columns]

In [202]:
df.sort_values(by='Data.Temperature.Max Temp', ascending=False).head()

Data.Precipitation   Date.Full  Date.Month  Date.Week of  Date.Year  \
9513                0.00  2016-07-31           7            31       2016   
9653                0.03  2016-07-31           7            31       2016   
9339                0.00  2016-07-24           7            24       2016   
6986                0.00  2016-06-05           6             5       2016   
7932                0.00  2016-06-26           6            26       2016   

     Station.City Station.Code Station.Location Station.State  \
9513   China Lake          NID   China Lake, CA    California   
9653    Las Vegas          LAS    Las Vegas, NV        Nevada   
9339    Las Vegas          LAS    Las Vegas, NV        Nevada   
6986      Phoenix          PHX      Phoenix, AZ       Arizona   
7932      Phoenix          PHX      Phoenix, AZ       Arizona   

      Data.Temperature.Avg Temp  Data.Temperature.Max Temp  \
9513                         93                        111   
9653                        100                        111   
9339                         98                        110   
6986                         95                        110   
7932                         99                        110   

      Data.Temperature.Min Temp  Data.Wind.Direction  Data.Wind.Speed  
9513                         75                   19             5.27  
9653                         88                   15             3.58  
9339                         85                   20             6.51  
6986                         79                   26             4.08  
7932                         88                   24             3.10

Some methods will operate on the index/columns, like `.sort_index()`:

In [203]:
df.sort_index(ascending=False)

Data.Precipitation   Date.Full  Date.Month  Date.Week of  Date.Year  \
16742                0.10  2017-01-01           1             1       2017   
16741                0.06  2017-01-01           1             1       2017   
16740                0.00  2017-01-01           1             1       2017   
16739                0.00  2017-01-01           1             1       2017   
16738                0.08  2017-01-01           1             1       2017   
...                   ...         ...         ...           ...        ...   
4                    0.01  2016-01-03           1             3       2016   
3                    0.00  2016-01-03           1             3       2016   
2                    0.16  2016-01-03           1             3       2016   
1                    0.00  2016-01-03           1             3       2016   
0                    0.00  2016-01-03           1             3       2016   

      Station.City Station.Code Station.Location Station.State  \
16742     Sheridan          SHR     Sheridan, WY       Wyoming   
16741      Rawlins          RWL      Rawlins, WY       Wyoming   
16740       Lander          LND       Lander, WY       Wyoming   
16739     Cheyenne          CYS     Cheyenne, WY       Wyoming   
16738       Casper          CPR       Casper, WY       Wyoming   
...            ...          ...              ...           ...   
4        Anchorage          ANC    Anchorage, AK        Alaska   
3       Montgomery          MGM   Montgomery, AL       Alabama   
2           Mobile          MOB       Mobile, AL       Alabama   
1       Huntsville          HSV   Huntsville, AL       Alabama   
0       Birmingham          BHM   Birmingham, AL       Alabama   

       Data.Temperature.Avg Temp  Data.Temperature.Max Temp  \
16742                         21                         34   
16741                         23                         31   
16740                         17                         29   
16739                         32                         42   
16738                         23                         32   
...                          ...                        ...   
4                             34                         38   
3                             45                         52   
2                             46                         51   
1                             39                         47   
0                             39                         46   

       Data.Temperature.Min Temp  Data.Wind.Direction  Data.Wind.Speed  
16742                          8                   23             7.51  
16741                         13                   24            18.16  
16740                          4                   26             1.65  
16739                         21                   26            15.16  
16738                         15                   23            19.98  
...                          ...                  ...              ...  
4                             29                   19             7.80  
3                             38                   32             6.86  
2                             41                   35             9.73  
1                             31                   32             3.86  
0                             32                   33             4.33  

[16743 rows x 14 columns]

## 10. Why ndarrays and Series and DataFrames?

At this point, you might be asking why we need all these different data structures. Well, they all serve different purposes and are suited to different tasks. For example:
- NumPy is typically faster/uses less memory than Pandas;
- not all Python packages are compatible with NumPy & Pandas;
- the ability to add labels to data can be useful (e.g., for time series);
- NumPy and Pandas have different built-in functions available.

My advice: use the simplest data structure that fulfills your needs!

Finally, we've seen how to go from: ndarray (`np.array()`) -> series (`pd.series()`) -> dataframe (`pd.DataFrame()`). Remember that we can also go the other way: dataframe/series -> ndarray using `df.to_numpy()`.