# Tutorial 2: Introduction to NumPy and Pandas

One of the most used packages within our discipline are NumPy and Pandas. This tutorial will focus on teaching you the basics of both of them.

```{admonition} Acknowledgements
This workbook is strongly based upon the work of others:
https://www.tomasbeuzen.com/python-programming-for-data-science/ 
```



<h2>Tutorial Outline<span class="tocSkip"></span></h2>
<hr>
<div class="toc"><ul class="toc-item">
<li><span><a href="#1.-Introduction-to-Python-Packages" data-toc-modified-id="1.-Introduction-to-Python-Packages-1">1. Introduction to Python Packages</a></span></li>
<li><span><a href="#2.-Introduction-to-NumPy" data-toc-modified-id="2.-Introduction-to-NumPy-2">2. Introduction to NumPy</a></span></li>
<li><span><a href="#3.-NumPy-Arrays" data-toc-modified-id="3.-NumPy-Arrays-23">3. NumPy Arrays</a></span></li>
<li><span><a href="#4.-Array-Operations-and-Broadcasting" data-toc-modified-id="4.-Array-Operations-and-Broadcasting-4">4. Array Operations and Broadcasting</a></span></li>
<li><span><a href="#5.-Indexing-and-slicing" data-toc-modified-id="5.-Indexing-and-slicing-5">5. Indexing and slicing</a></span></li>
<li><span><a href="#6.-More-Useful-NumPy-Functions" data-toc-modified-id="6.-More-Useful-NumPy-Functions-6">6. More Useful NumPy Functions</a></span></li>
<li><span><a href="#7.-Introduction-to-Pandas" data-toc-modified-id="7.-Introduction-to-Pandas-7">7. Introduction to Pandas</a></span></li>
<li><span><a href="#8.-Pandas-Series" data-toc-modified-id="8.-Pandas-Series-8">8. Pandas Series</a></span></li>
<li><span><a href="#9.-Pandas-DataFrames" data-toc-modified-id="9.-Pandas-DataFrames-9">9. Pandas DataFrames</a></span></li>
<li><span><a href="#10.-Why-ndarrays-and-Series-and-DataFrames?" data-toc-modified-id="10.-Why-ndarrays-and-Series-and-DataFrames?-10">10. Why ndarrays and Series and DataFrames?</a></span></li></ul></div>

## Chapter Learning Objectives
<hr>

**NumPy**
- Use NumPy to create arrays with built-in functions inlcuding `np.array()`, `np.arange()`, `np.linspace()` and `np.full()`, `np.zeros()`, `np.ones()`
- Be able to access values from a NumPy array by numeric indexing and slicing and boolean indexing
- Perform mathematical operations on and with arrays.
- Explain what broadcasting is and how to use it.
- Reshape arrays by adding/removing/reshaping axes with `.reshape()`, `np.newaxis()`, `.ravel()`, `.flatten()`
- Understand how to use built-in NumPy functions like `np.sum()`, `np.mean()`, `np.log()` as stand alone functions or as methods of numpy arrays (when available)

**Pandas**
- Create Pandas series with `pd.Series()` and Pandas dataframe with `pd.DataFrame()`
- Be able to access values from a Series/DataFrame by indexing, slicing and boolean indexing using notation such as `df[]`, `df.loc[]`, `df.iloc[]`, `df.query[]`
- Perform basic arithmetic operations between two series and anticipate the result.
- Describe how Pandas assigns dtypes to Series and what the `object` dtype is
- Read a standard .csv file from a local path or url using Pandas `pd.read_csv()`.
- Explain the relationship and differences between `np.ndarray`, `pd.Series` and `pd.DataFrame` objects in Python.

## 1. Introduction to Python Packages
<hr>

Packages are an essential building block in programming. Without packages, we’d spend lots of time writing code that’s already been written. Imagine having to write code from scratch every time you wanted to parse a file in a particular format. You’d never get anything done! That’s why we always want to use packages.

To understand Python packages, we’ll briefly need to look at scripts and modules. A *script* is something you execute in the shell to accomplish a defined task. To write a script, you’d type your code into your favorite text editor and save it with the .py extension. You can then use the python command in a terminal to execute your script. 

A module on the other hand is a Python program that you import, either in interactive mode or into your other programs. “Module” is really an umbrella term for reusable code.

A Python package usually consists of several modules. Physically, a package is a folder containing modules and maybe other folders that themselves may contain more folders and modules. Conceptually, it’s a namespace. This simply means that a package’s modules are bound together by a package name, by which they may be referenced.


### Importing a package

We’ll import a package using the import statement:

```python
import <package>
```

## 2. Introduction to NumPy
<hr>

<img src="../_static/images/numpy.png" class="bg-primary"

NumPy stands for "Numerical Python" and it is the standard Python library used for working with arrays (i.e., vectors & matrices), linear algerba, and other numerical computations. NumPy is written in C, making NumPy arrays faster and more memory efficient than Python lists or arrays, read more: ([link 1](https://www.datadiscuss.com/proof-that-numpy-is-much-faster-than-normal-python-array/), [link 2](https://www.jessicayung.com/numpy-arrays-memory-and-strides/), [link 3](https://www.labri.fr/perso/nrougier/from-python-to-numpy/)).

NumPy can be installed using `conda` (if not already):

```
conda install numpy
```

## 3. NumPy Arrays
<hr>

### What are Arrays?

Arrays are "n-dimensional" data structures that can contain all the basic Python data types, e.g., floats, integers, strings etc, but work best with numeric data. NumPy arrays ("ndarrays") are homogenous, which means that items in the array should be of the same type. ndarrays are also compatible with numpy's vast collection of in-built functions!

![](img/chapter5/numpy_arrays.png)

Source: [Medium.com](https://medium.com/hackernoon/10-machine-learning-data-science-and-deep-learning-courses-for-programmers-7edc56078cde)

Usually we import numpy with the alias `np` (to avoid having to type out n-u-m-p-y every time we want to use it):

In [ ]:
import numpy as np

A numpy array is sort of like a list:

In [ ]:
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [ ]:
my_array = np.array([1, 2, 3, 4, 5])
my_array

array([1, 2, 3, 4, 5])

But it has the type `ndarray`:

In [ ]:
type(my_array)

numpy.ndarray

Unlike a list, arrays can only hold a single type (usually numbers):

In [ ]:
my_list = [1, "hi"]
my_list

[1, 'hi']

In [ ]:
my_array = np.array((1, "hi"))
my_array

array(['1', 'hi'], dtype='<U21')

Above: NumPy converted the integer `1` into the string `'1'`!

### Creating arrays

ndarrays are typically created using two main methods:
1. From existing data (usually lists or tuples) using `np.array()`, like we saw above; or,
2. Using built-in functions such as `np.arange()`, `np.linspace()`, `np.zeros()`, etc.

In [ ]:
my_list = [1, 2, 3]
np.array(my_list)

array([1, 2, 3])

Just like you can have "multi-dimensional lists" (by nesting lists in lists), you can have multi-dimensional arrays (indicated by double square brackets `[[ ]]`):

In [ ]:
list_2d = [[1, 2], [3, 4], [5, 6]]
list_2d

[[1, 2], [3, 4], [5, 6]]

In [ ]:
array_2d = np.array(list_2d)
array_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

You'll probably use the built-in numpy array creators quite often. Here are some common ones (hint - don't forget to check the docstrings for help with these functions, if you're in Jupyter, remeber the `shift + tab` shortcut):

In [ ]:
np.arange(1, 5)  # from 1 inclusive to 5 exclusive

array([1, 2, 3, 4])

In [ ]:
np.arange(0, 11, 2)  # step by 2 from 1 to 11

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.linspace(0, 10, 5)  # 5 equally spaced points between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.ones((2, 2))  # an array of ones with size 2 x 2

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((2, 3))  # an array of zeros with size 2 x 3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.full((3, 3), 3.14)  # an array of the number 3.14 with size 3 x 3

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [ ]:
np.full((3, 3, 3), 3.14)  # an array of the number 3.14 with size 3 x 3 x 3

array([[[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]]])

In [ ]:
np.random.rand(5, 2)  # random numbers uniformly distributed from 0 to 1 with size 5 x 2

array([[0.99572773, 0.81999212],
       [0.97339833, 0.10561435],
       [0.85923126, 0.40018929],
       [0.97506147, 0.78313652],
       [0.99229906, 0.14525197]])

There are many useful attributes/methods that can be called off numpy arrays:

In [ ]:
print(dir(np.ndarray))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [ ]:
x = np.random.rand(5, 2)
x

array([[0.0252237 , 0.3368265 ],
       [0.57678161, 0.68709061],
       [0.00721254, 0.61280414],
       [0.65886063, 0.87372073],
       [0.82815125, 0.47996047]])

In [ ]:
x.transpose()

array([[0.0252237 , 0.57678161, 0.00721254, 0.65886063, 0.82815125],
       [0.3368265 , 0.68709061, 0.61280414, 0.87372073, 0.47996047]])

In [ ]:
x.mean()

0.5086632185578763

In [ ]:
x.astype(int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

### Array Shapes

As you just saw above, arrays can be of any dimension, shape and size you desire. In fact, there are three main array attributes you need to know to work out the characteristics of an array:
- `.ndim`: the number of dimensions of an array
- `.shape`: the number of elements in each dimension (like calling `len()` on each dimension)
- `.size`: the total number of elements in an array (i.e., the product of `.shape`)

In [ ]:
array_1d = np.ones(3)
print(f"Dimensions: {array_1d.ndim}")
print(f"     Shape: {array_1d.shape}")
print(f"      Size: {array_1d.size}")

Dimensions: 1
     Shape: (3,)
      Size: 3


Let's turn that print action into a function and try out some other arrays:

In [ ]:
def print_array(x):
    print(f"Dimensions: {x.ndim}")
    print(f"     Shape: {x.shape}")
    print(f"      Size: {x.size}")
    print("")
    print(x)

In [ ]:
array_2d = np.ones((3, 2))
print_array(array_2d)

Dimensions: 2
     Shape: (3, 2)
      Size: 6

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
array_4d = np.ones((1, 2, 3, 4))
print_array(array_4d)

Dimensions: 4
     Shape: (1, 2, 3, 4)
      Size: 24

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]


After 3 dimensions, printing arrays starts getting pretty messy. As you can see above, the number of square brackets (`[ ]`) in the printed output indicate how many dimensions there are: for example, above, the output starts with 4 square brackets `[[[[` indicative of a 4D array.

### 1-d Arrays

One of the most confusing things about numpy is 1-d arrays (vectors) can have 3 possible shapes!

In [ ]:
x = np.ones(5)
print_array(x)

Dimensions: 1
     Shape: (5,)
      Size: 5

[1. 1. 1. 1. 1.]


In [ ]:
y = np.ones((1, 5))
print_array(y)

Dimensions: 2
     Shape: (1, 5)
      Size: 5

[[1. 1. 1. 1. 1.]]


In [ ]:
z = np.ones((5, 1))
print_array(z)

Dimensions: 2
     Shape: (5, 1)
      Size: 5

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


We can use `np.array_equal()` to determine if two arrays have the same shape and elements:

In [ ]:
np.array_equal(x, x)

True

In [ ]:
np.array_equal(x, y)

False

In [ ]:
np.array_equal(x, z)

False

In [ ]:
np.array_equal(y, z)

False

The shape of your 1-d arrays can actually have big implications on your mathematical oeprations!

In [ ]:
print(f"x: {x}")
print(f"y: {y}")
print(f"z: {z}")

x: [1. 1. 1. 1. 1.]
y: [[1. 1. 1. 1. 1.]]
z: [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [ ]:
x + y  # makes sense

array([[2., 2., 2., 2., 2.]])

In [ ]:
y + z  # wait, what?

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

What happened in the cell above is "broadcasting" and we'll discuss it below.

## 4. Array Operations and Broadcasting
<hr>

### Elementwise operations

Elementwise operations refer to operations applied to each element of an array or between the paired elements of two arrays.

In [ ]:
x = np.ones(4)
x

array([1., 1., 1., 1.])

In [ ]:
y = x + 1
y

array([2., 2., 2., 2.])

In [ ]:
x - y

array([-1., -1., -1., -1.])

In [ ]:
x == y

array([False, False, False, False])

In [ ]:
x * y

array([2., 2., 2., 2.])

In [ ]:
x ** y

array([1., 1., 1., 1.])

In [ ]:
x / y

array([0.5, 0.5, 0.5, 0.5])

In [ ]:
np.array_equal(x, y)

False

### Broadcasting

ndarrays with different sizes cannot be directly used in arithmetic operations:

In [ ]:
a = np.ones((2, 2))
b = np.ones((3, 3))
a + b

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

`Broadcasting` describes how NumPy treats arrays with different shapes during arithmetic operations. The idea is to wrangle data so that operations can occur element-wise.

Let's see an example. Say I sell pies on my weekends. I sell 3 types of pies at different prices, and I sold the following number of each pie last weekend. I want to know how much money I made per pie type per day.

![](img/chapter5/pies.png)

In [ ]:
cost = np.array([20, 15, 25])
print("Pie cost:")
print(cost)
sales = np.array([[2, 3, 1], [6, 3, 3], [5, 3, 5]])
print("\nPie sales (#):")
print(sales)

Pie cost:
[20 15 25]

Pie sales (#):
[[2 3 1]
 [6 3 3]
 [5 3 5]]


How can we multiply these two arrays together? We could use a loop:

![](img/chapter5/pies_loop.png)

In [ ]:
total = np.zeros((3, 3))  # initialize an array of 0's
for col in range(sales.shape[1]):
    total[:, col] = sales[:, col] * cost
total

array([[ 40.,  60.,  20.],
       [ 90.,  45.,  45.],
       [125.,  75., 125.]])

Or we could make them the same size, and multiply corresponding elements "elementwise":

![](img/chapter5/pies_broadcast.png)

In [ ]:
cost = np.repeat(cost, 3).reshape((3, 3))
cost

array([[20, 20, 20],
       [15, 15, 15],
       [25, 25, 25]])

In [ ]:
cost * sales

array([[ 40,  60,  20],
       [ 90,  45,  45],
       [125,  75, 125]])

Congratulations! You just broadcasted! Broadcasting is just Numpy eessentially doing the `np.repeat()` for you under the hood:

In [ ]:
cost = np.array([20, 15, 25]).reshape(3, 1)
print(f" cost shape: {cost.shape}")
sales = np.array([[2, 3, 1], [6, 3, 3], [5, 3, 5]])
print(f"sales shape: {sales.shape}")

 cost shape: (3, 1)
sales shape: (3, 3)


In [ ]:
sales * cost

array([[ 40,  60,  20],
       [ 90,  45,  45],
       [125,  75, 125]])

In NumPy the smaller array is “broadcast” across the larger array so that they have compatible shapes:

![](img/chapter5/broadcasting.png)

Source: [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/) by Jake VanderPlas (2016)

Why should you care about broadcasting? Well, it's cleaner and faster than looping and it also affects the array shapes resulting from arithmetic operations. Below, we can time how long it takes to loop vs broadcast:

In [ ]:
cost = np.array([20, 15, 25]).reshape(3, 1)
sales = np.array([[2, 3, 1],
                  [6, 3, 3],
                  [5, 3, 5]])
total = np.zeros((3, 3))

time_loop = %timeit -q -o -r 3 for col in range(sales.shape[1]): total[:, col] = sales[:, col] * np.squeeze(cost)
time_vec = %timeit -q -o -r 3 cost * sales
print(f"Broadcasting is {time_loop.average / time_vec.average:.2f}x faster than looping here.")

Broadcasting is 8.67x faster than looping here.


Of course, not all arrays are compatible! NumPy compares arrays element-wise. It starts with the trailing dimensions, and works its way forward. Dimensions are compatible if:
- **they are equal**, or
- **one of them is 1**.

Use the code below to test out array compatibitlity:

In [ ]:
a = np.ones((3, 2))
b = np.ones((3, 2, 1))
print(f"The shape of a is: {a.shape}")
print(f"The shape of b is: {b.shape}")
print("")
try:
    print(f"The shape of a + b is: {(a + b).shape}")
except:
    print(f"ERROR: arrays are NOT broadcast compatible!")

The shape of a is: (3, 2)
The shape of b is: (3, 2, 1)

ERROR: arrays are NOT broadcast compatible!


### Reshaping Arrays

There are 3 key reshaping methods I want you to know about for reshaping numpy arrays:
- `.rehshape()`
- `np.newaxis`
- `.ravel()`/`.flatten()`

In [ ]:
x = np.full((4, 3), 3.14)
x

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

You'll reshape arrays farily often and the `.reshape()` method is pretty intuitive:

In [ ]:
x.reshape(6, 2)

array([[3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14]])

In [ ]:
x.reshape(2, -1)  # using -1 will calculate the dimension for you (if possible)

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
a = np.ones(3)
print_array(a)
b = np.ones((3, 2))
print_array(b)

Dimensions: 1
     Shape: (3,)
      Size: 3

[1. 1. 1.]
Dimensions: 2
     Shape: (3, 2)
      Size: 6

[[1. 1.]
 [1. 1.]
 [1. 1.]]


If I want to add these two arrays I won't be able to because their dimensions are not compatible:

In [ ]:
a + b

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

Sometimes you'll want to add dimensions to an array for broadcasting purposes like this. We can do that with `np.newaxis` (note that `None` is an alias for `np.newaxis`). We can add a dimension to `a` to make the arrays compatible:

In [ ]:
print_array(a[:, np.newaxis])  # same as a[:, None]

Dimensions: 2
     Shape: (3, 1)
      Size: 3

[[1.]
 [1.]
 [1.]]


In [ ]:
a[:, np.newaxis] + b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

Finally, sometimes you'll want to "flatten" arrays to a single dimension using `.ravel()` or `.flatten()`. `.flatten()` used to return a copy and `.ravel()` a view/reference but now they both return a copy so I can't think of an important reason to use one over the other 🤷‍♂️

In [ ]:
x

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [ ]:
print_array(x.flatten())

Dimensions: 1
     Shape: (12,)
      Size: 12

[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]


In [ ]:
print_array(x.ravel())

Dimensions: 1
     Shape: (12,)
      Size: 12

[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]


## 5. Indexing and slicing
<hr>

Concepts of indexing should be pretty familiar by now. Indexing arrays is similar to indexing lists but there are just more dimensions.

### Numeric Indexing

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[3]

3

In [ ]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:4]

array([0, 1, 2, 3])

In [ ]:
x[2:5]

array([2, 3, 4])

In [ ]:
x[2:3]

array([2])

In [ ]:
x[-1]

9

In [ ]:
x[-2]

8

In [ ]:
x[5:0:-1]

array([5, 4, 3, 2, 1])

For 2D arrays:

In [ ]:
x = np.random.randint(10, size=(4, 6))
x

array([[9, 5, 0, 2, 3, 4],
       [0, 8, 2, 1, 0, 7],
       [0, 9, 4, 2, 9, 0],
       [4, 4, 0, 8, 3, 9]])

In [ ]:
x[3, 4]  # do this

3

In [ ]:
x[3][4]  # i do not like this as much

3

In [ ]:
x[3]

array([4, 4, 0, 8, 3, 9])

In [ ]:
len(x)  # generally, just confusing

4

In [ ]:
x.shape

(4, 6)

In [ ]:
x[:, 2]  # column number 2

array([0, 2, 4, 0])

In [ ]:
x[2:, :3]

array([[0, 9, 4],
       [4, 4, 0]])

In [ ]:
x.T

array([[9, 0, 0, 4],
       [5, 8, 9, 4],
       [0, 2, 4, 0],
       [2, 1, 2, 8],
       [3, 0, 9, 3],
       [4, 7, 0, 9]])

In [ ]:
x

array([[9, 5, 0, 2, 3, 4],
       [0, 8, 2, 1, 0, 7],
       [0, 9, 4, 2, 9, 0],
       [4, 4, 0, 8, 3, 9]])

In [ ]:
x[1, 1] = 555555
x

array([[     9,      5,      0,      2,      3,      4],
       [     0, 555555,      2,      1,      0,      7],
       [     0,      9,      4,      2,      9,      0],
       [     4,      4,      0,      8,      3,      9]])

In [ ]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [ ]:
z[0] = 5
z

array([5., 0., 0., 0., 0.])

### Boolean Indexing

In [ ]:
x = np.random.rand(10)
x

array([0.59134864, 0.18116891, 0.07089194, 0.71975976, 0.95339547,
       0.71630937, 0.80956702, 0.94886201, 0.58996084, 0.03238515])

In [ ]:
x + 1

array([1.59134864, 1.18116891, 1.07089194, 1.71975976, 1.95339547,
       1.71630937, 1.80956702, 1.94886201, 1.58996084, 1.03238515])

In [ ]:
x_thresh = x > 0.5
x_thresh

array([ True, False, False,  True,  True,  True,  True,  True,  True,
       False])

In [ ]:
x[x_thresh] = 0.5  # set all elements  > 0.5 to be equal to 0.5
x

array([0.5       , 0.18116891, 0.07089194, 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.03238515])

In [ ]:
x = np.random.rand(10)
x

array([0.62912775, 0.82278712, 0.26534708, 0.8847088 , 0.48882526,
       0.04902107, 0.55230008, 0.6579308 , 0.24630664, 0.77826484])

In [ ]:
x[x > 0.5] = 0.5
x

array([0.5       , 0.5       , 0.26534708, 0.5       , 0.48882526,
       0.04902107, 0.5       , 0.5       , 0.24630664, 0.5       ])

## 6. More Useful NumPy Functions

Numpy has many built-in functions for mathematical operations, really it has almost every numerical operation you might want to do in its library. I'm not going to explore the whole library here, but as an example of some of the available functions, consider working out the hypotenuse of a triangle that with sides 3m and 4m:

![](img/chapter5/triangle.png)

In [ ]:
sides = np.array([3, 4])

There are several ways we could solve this problem. We could directly use Pythagoras's Theorem:

$$c = \sqrt{a^2+b^2}$$

In [ ]:
np.sqrt(np.sum([np.power(sides[0], 2), np.power(sides[1], 2)]))

5.0

We can leverage the fact that we're dealing with a numpy array and apply a "vectorized" operation (more on that in a bit) to the whole vector at one time:

In [ ]:
(sides ** 2).sum() ** 0.5

5.0

Or we can simply use a numpy built-in function (if it exists):

In [ ]:
np.linalg.norm(sides)  # you'll learn more about norms in 573

5.0

In [ ]:
np.hypot(*sides)

5.0

### Vectorization

Broadly speaking, "vectorization" in NumPy refers to the use of optmized C code to perform an operation. Long-story-short, because numpy arrays are homogenous (contain the same dtype), we don't need to check that we can perform an operation on elements of a sequence before we do the operation which results in a huge speed-up. You can kind of think of this concept as NumPy being able to perform an operation on the whole array at the same time rather than one-by-one (this is not actually the case, a super-efficient C loop is still running under the hood, but that's an irrelevant detail). You can read more about vectorization [here](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/VectorizedOperations.html) but all you need to know is that most operations in NumPy are vectorized, so just try to do things at an "array-level" rather than an "element-level", e.g.:

In [ ]:
# DONT DO THIS
array = np.array(range(5))
for i, element in enumerate(array):
    array[i] = element ** 2
array

array([ 0,  1,  4,  9, 16])

In [ ]:
# DO THIS
array = np.array(range(5))
array **= 2 

Let's do a quick timing experiment:

In [ ]:
# loop method
array = np.array(range(5))
time_loop = %timeit -q -o -r 3 for i, element in enumerate(array): array[i] = element ** 2
# vectorized method
array = np.array(range(5))
time_vec = %timeit -q -o -r 3 array ** 2
print(f"Vectorized operation is {time_loop.average / time_vec.average:.2f}x faster than looping here.")

Vectorized operation is 4.57x faster than looping here.


![](../docs/banner.png)

## 7. Introduction to Pandas
<hr>

![](img/chapter7/pandas.png)

Pandas is most popular Python library for tabular data structures. You can think of Pandas as an extremely powerful version of Excel (but free and with a lot more features!) 

Pandas can be installed using `conda`:

```
conda install pandas
```

We usually import pandas with the alias `pd`. You'll see these two imports at the top of most data science workflows:

In [ ]:
import pandas as pd
import numpy as np

## 8. Pandas Series
<hr>

### What are Series?

A Series is like a NumPy array but with labels. They are strictly 1-dimensional and can contain any data type (integers, strings, floats, objects, etc), including a mix of them. Series can be created from a scalar, a list, ndarray or dictionary using `pd.Series()` (**note the captial "S"**). Here are some example series:

![](img/chapter7/series.png)

### Creating Series

By default, series are labelled with indices starting from 0. For example:

In [ ]:
pd.Series(data = [-5, 1.3, 21, 6, 3])

0    -5.0
1     1.3
2    21.0
3     6.0
4     3.0
dtype: float64

But you can add a custom index:

In [ ]:
pd.Series(data = [-5, 1.3, 21, 6, 3],
          index = ['a', 'b', 'c', 'd', 'e'])

a    -5.0
b     1.3
c    21.0
d     6.0
e     3.0
dtype: float64

You can create a Series from a dictionary:

In [ ]:
pd.Series(data = {'a': 10, 'b': 20, 'c': 30})

a    10
b    20
c    30
dtype: int64

Or from an ndarray:

In [ ]:
pd.Series(data = np.random.randn(3))

0   -0.428301
1   -0.104959
2    0.170835
dtype: float64

Or even a scalar:

In [ ]:
pd.Series(3.141)

0    3.141
dtype: float64

In [ ]:
pd.Series(data=3.141, index=['a', 'b', 'c'])

a    3.141
b    3.141
c    3.141
dtype: float64

### Series Characteristics

Series can be given a `name` attribute. I almost never use this but it might come up sometimes:

In [ ]:
s = pd.Series(data = np.random.randn(5), name='random_series')
s

0   -1.363190
1    0.425801
2   -0.048966
3   -0.298172
4    1.899199
Name: random_series, dtype: float64

In [ ]:
s.name

'random_series'

In [ ]:
s.rename("another_name")

0   -1.363190
1    0.425801
2   -0.048966
3   -0.298172
4    1.899199
Name: another_name, dtype: float64

You can access the index labels of your series using the `.index` attribute:

In [ ]:
s.index

RangeIndex(start=0, stop=5, step=1)

You can access the underlying data array using `.to_numpy()`:

In [ ]:
s.to_numpy()

array([-1.36319006,  0.42580052, -0.04896627, -0.29817227,  1.89919866])

In [ ]:
pd.Series([[1, 2, 3], "b", 1]).to_numpy()

array([list([1, 2, 3]), 'b', 1], dtype=object)

### Indexing and Slicing Series

Series are very much like ndarrays (in fact, series can be passed to most NumPy functions!). They can be indexed using square brackets `[ ]` and sliced using colon `:` notation:

In [ ]:
s = pd.Series(data = range(5),
              index = ['A', 'B', 'C', 'D', 'E'])
s

A    0
B    1
C    2
D    3
E    4
dtype: int64

In [ ]:
s[0]

0

In [ ]:
s[[1, 2, 3]]

B    1
C    2
D    3
dtype: int64

In [ ]:
s[0:3]

A    0
B    1
C    2
dtype: int64

Note above how array-based indexing and slicing also returns the series index.

Series are also like dictionaries, in that we can access values using index labels:

In [ ]:
s["A"]

0

In [ ]:
s[["B", "D", "C"]]

B    1
D    3
C    2
dtype: int64

In [ ]:
s["A":"C"]

A    0
B    1
C    2
dtype: int64

In [ ]:
"A" in s

True

In [ ]:
"Z" in s

False

Series do allow for non-unique indexing, but **be careful** because indexing operations won't return unique values:

In [ ]:
x = pd.Series(data = range(5),
              index = ["A", "A", "A", "B", "C"])
x

A    0
A    1
A    2
B    3
C    4
dtype: int64

In [ ]:
x["A"]

A    0
A    1
A    2
dtype: int64

Finally, we can also do boolean indexing with series:

In [ ]:
s[s >= 1]

B    1
C    2
D    3
E    4
dtype: int64

In [ ]:
s[s > s.mean()]

D    3
E    4
dtype: int64

In [ ]:
(s != 1)

A     True
B    False
C     True
D     True
E     True
dtype: bool

### Series Operations

Unlike ndarrays operations between Series (+, -, /, \*) align values based on their **LABELS** (not their position in the structure). The resulting index will be the __*sorted union*__ of the two indexes. This gives you the flexibility to run operations on series regardless of their labels.

In [ ]:
s1 = pd.Series(data = range(4),
               index = ["A", "B", "C", "D"])
s1

A    0
B    1
C    2
D    3
dtype: int64

In [ ]:
s2 = pd.Series(data = range(10, 14),
               index = ["B", "C", "D", "E"])
s2

B    10
C    11
D    12
E    13
dtype: int64

In [ ]:
s1 + s2

A     NaN
B    11.0
C    13.0
D    15.0
E     NaN
dtype: float64

As you can see above, indices that match will be operated on. Indices that don't match will appear in the product but with `NaN` values:

![](img/chapter7/series_addition.png)

We can also perform standard operations on a series, like multiplying or squaring. NumPy also accepts series as an argument to most functions because series are built off numpy arrays (more on that later):

In [ ]:
s1 ** 2

A    0
B    1
C    4
D    9
dtype: int64

In [ ]:
np.exp(s1)

A     1.000000
B     2.718282
C     7.389056
D    20.085537
dtype: float64

Finally, just like arrays, series have many built-in methods for various operations. You can find them all by running `help(pd.Series)`:

In [ ]:
print([_ for _ in dir(pd.Series) if not _.startswith("_")])  # print all common methods

['T', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'append', 'apply', 'argmax', 'argmin', 'argsort', 'array', 'asfreq', 'asof', 'astype', 'at', 'at_time', 'attrs', 'autocorr', 'axes', 'backfill', 'between', 'between_time', 'bfill', 'bool', 'cat', 'clip', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'divmod', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dt', 'dtype', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'ewm', 'expanding', 'explode', 'factorize', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'floordiv', 'ge', 'get', 'groupby', 'gt', 'hasnans', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'interpolate', 'is_monotonic', 'is_monotonic_decreasing', 'is_monotonic_increasing', 'is_unique', 'isin', 'isna', 'isnull', 'item', 'items', 'iteritems', 'keys', 'kurt', 'kur

In [ ]:
s1

A    0
B    1
C    2
D    3
dtype: int64

In [ ]:
s1.mean()

1.5

In [ ]:
s1.sum()

6

In [ ]:
s1.astype(float)

A    0.0
B    1.0
C    2.0
D    3.0
dtype: float64

**"Chaining"** operations together is also common with pandas:

In [ ]:
s1.add(3.141).pow(2).mean().astype(int)

22

### Data Types

Series can hold all the data types (`dtypes`) you're used to, e.g., `int`, `float`, `bool`, etc. There are a few other special data types too (`object`, `DateTime` and `Categorical`) which we'll talk about in this and later chapters. You can always read more about pandas dtypes [in the documentation too](https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html#dtypes). For example, here's a series of `dtype` int64:

In [ ]:
x = pd.Series(range(5))
x.dtype

dtype('int64')

The dtype "`object`" is used for series of strings or mixed data. Pandas is [currently experimenting](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.StringDtype.html#pandas.StringDtype) with a dedicated string dtype `StringDtype`, but it is still in testing.

In [ ]:
x = pd.Series(['A', 'B'])
x

0    A
1    B
dtype: object

In [ ]:
x = pd.Series(['A', 1, ["I", "AM", "A", "LIST"]])
x

0                   A
1                   1
2    [I, AM, A, LIST]
dtype: object

While flexible, it is recommended to avoid the use of `object` dtypes because of higher memory requirements. Essentially, in an `object` dtype series, every single element stores information about its individual dtype. We can inspect the dtypes of all the elements in a mixed series in several ways, below I'll use the `map` method:

In [ ]:
x.map(type)

0     <class 'str'>
1     <class 'int'>
2    <class 'list'>
dtype: object

We can see that each object in our series has a different dtype. This comes at a cost. Compare the [memory usage](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.memory_usage.html) of the series below:

In [ ]:
x1 = pd.Series([1, 2, 3])
print(f"x1 dtype: {x1.dtype}")
print(f"x1 memory usage: {x1.memory_usage(deep=True)} bytes")
print("")
x2 = pd.Series([1, 2, "3"])
print(f"x2 dtype: {x2.dtype}")
print(f"x2 memory usage: {x2.memory_usage(deep=True)} bytes")
print("")
x3 = pd.Series([1, 2, "3"]).astype('int8')  # coerce the object series to int8
print(f"x3 dtype: {x3.dtype}")
print(f"x3 memory usage: {x3.memory_usage(deep=True)} bytes")

x1 dtype: int64
x1 memory usage: 152 bytes

x2 dtype: object
x2 memory usage: 258 bytes

x3 dtype: int8
x3 memory usage: 131 bytes


In summary, try to use uniform dtypes where possible - they are more memory efficient!

One more gotcha, `NaN` (frequently used to represent missing values in data) is a float:

In [ ]:
type(np.NaN)

float

This can be problematic if you have a series of integers and one missing value, because Pandas will cast the whole series to a float:

In [ ]:
pd.Series([1, 2, 3, np.NaN])

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

Only recently, Pandas has implemented a "[nullable integer dtype](https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html)", which can handle `NaN` in an integer series without affecting the `dtype`. Note the captial "I" in the type below, differentiating it from numpy's `int64` dtype:

In [ ]:
pd.Series([1, 2, 3, np.NaN]).astype('Int64')

0       1
1       2
2       3
3    <NA>
dtype: Int64

This is not the default in Pandas yet and functionality of this new feature is still subject to change.

## 9. Pandas DataFrames
<hr>

### What are DataFrames?

Pandas DataFrames are you're new best friend. They are like the Excel spreadsheets you may be used to. DataFrames are really just Series stuck together! Think of a DataFrame as a dictionary of series, with the "keys" being the column labels and the "values" being the series data:

![](img/chapter7/dataframe.png)

### Creating DataFrames

Dataframes can be created using `pd.DataFrame()` (note the capital "D" and "F"). Like series, index and column labels of dataframes are labelled starting from 0 by default:

In [ ]:
pd.DataFrame([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

We can use the `index` and `columns` arguments to give them labels:

In [ ]:
pd.DataFrame([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]],
             index = ["R1", "R2", "R3"],
             columns = ["C1", "C2", "C3"])

C1  C2  C3
R1   1   2   3
R2   4   5   6
R3   7   8   9

There are so many ways to create dataframes. I most often create them from dictionaries or ndarrays:

In [ ]:
pd.DataFrame({"C1": [1, 2, 3],
              "C2": ['A', 'B', 'C']},
             index=["R1", "R2", "R3"])

C1 C2
R1   1  A
R2   2  B
R3   3  C

In [ ]:
pd.DataFrame(np.random.randn(5, 5),
             index=[f"row_{_}" for _ in range(1, 6)],
             columns=[f"col_{_}" for _ in range(1, 6)])

col_1     col_2     col_3     col_4     col_5
row_1 -1.511598 -1.073875  2.990474  2.408082  0.101569
row_2  0.767246  0.423030 -0.135450  0.369545  0.761417
row_3  0.714677  1.489430  0.843088 -1.284666  1.310033
row_4 -0.513656  0.539531  0.207057  0.425888  0.481794
row_5 -1.361988 -0.479158  0.158281 -0.196813  0.136745

In [ ]:
pd.DataFrame(np.array([['Tom', 7], ['Mike', 15], ['Tiffany', 3]]))

0   1
0      Tom   7
1     Mike  15
2  Tiffany   3

Here's a table of the main ways you can create dataframes (see the [Pandas documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/dsintro.html#dataframe) for more):

|Create DataFrame from|Code|
|---|---|
|Lists of lists|`pd.DataFrame([['Tom', 7], ['Mike', 15], ['Tiffany', 3]])`|
|ndarray|`pd.DataFrame(np.array([['Tom', 7], ['Mike', 15], ['Tiffany', 3]]))`|
|Dictionary|`pd.DataFrame({"Name": ['Tom', 'Mike', 'Tiffany'], "Number": [7, 15, 3]})`|
|List of tuples|`pd.DataFrame(zip(['Tom', 'Mike', 'Tiffany'], [7, 15, 3]))`|
|Series|`pd.DataFrame({"Name": pd.Series(['Tom', 'Mike', 'Tiffany']), "Number": pd.Series([7, 15, 3])})`|


### Indexing and Slicing DataFrames

There are several main ways to select data from a DataFrame:
1. `[]`
2. `.loc[]`
3. `.iloc[]`
4. Boolean indexing
5. `.query()`

In [ ]:
df = pd.DataFrame({"Name": ["Tom", "Mike", "Tiffany"],
                   "Language": ["Python", "Python", "R"],
                   "Courses": [5, 4, 7]})
df

Name Language  Courses
0      Tom   Python        5
1     Mike   Python        4
2  Tiffany        R        7

#### Indexing with `[]`
Select columns by single labels, lists of labels, or slices:

In [ ]:
df['Name']  # returns a series

0        Tom
1       Mike
2    Tiffany
Name: Name, dtype: object

In [ ]:
df[['Name']]  # returns a dataframe!

Name
0      Tom
1     Mike
2  Tiffany

In [ ]:
df[['Name', 'Language']]

Name Language
0      Tom   Python
1     Mike   Python
2  Tiffany        R

You can only index rows by using slices, not single values (but not recommended, see preferred methods below).

In [ ]:
df[0] # doesn't work

KeyError: 0

In [ ]:
df[0:1] # does work

Name Language  Courses
0  Tom   Python        5

In [ ]:
df[1:] # does work

Name Language  Courses
1     Mike   Python        4
2  Tiffany        R        7

#### Indexing with `.loc` and `.iloc`
Pandas created the methods `.loc[]` and `.iloc[]` as more flexible alternatives for accessing data from a dataframe. Use `df.iloc[]` for indexing with integers and `df.loc[]` for indexing with labels. These are typically the [recommended methods of indexing](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated) in Pandas.

In [ ]:
df

Name Language  Courses
0      Tom   Python        5
1     Mike   Python        4
2  Tiffany        R        7

First we'll try out `.iloc` which accepts *integers* as references to rows/columns:

In [ ]:
df.iloc[0]  # returns a series

Name           Tom
Language    Python
Courses          5
Name: 0, dtype: object

In [ ]:
df.iloc[0:2]  # slicing returns a dataframe

Name Language  Courses
0   Tom   Python        5
1  Mike   Python        4

In [ ]:
df.iloc[2, 1]  # returns the indexed object

'R'

In [ ]:
df.iloc[[0, 1], [1, 2]]  # returns a dataframe

Language  Courses
0   Python        5
1   Python        4

Now let's look at `.loc` which accepts *labels* as references to rows/columns:

In [ ]:
df.loc[:, 'Name']

0        Tom
1       Mike
2    Tiffany
Name: Name, dtype: object

In [ ]:
df.loc[:, 'Name':'Language']

Name Language
0      Tom   Python
1     Mike   Python
2  Tiffany        R

In [ ]:
df.loc[[0, 2], ['Language']]

Language
0   Python
2        R

Sometimes we want to use a mix of integers and labels to reference data in a dataframe. The easiest way to do this is to use `.loc[]` with a label then use an integer in combinations with `.index` or `.columns`:

In [ ]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
df.columns

Index(['Name', 'Language', 'Courses'], dtype='object')

In [ ]:
df.loc[df.index[0], 'Courses']  # I want to reference the first row and the column named "Courses"

5

In [ ]:
df.loc[2, df.columns[1]]  # I want to reference row "2" and the second column

'R'

#### Boolean indexing
Just like with series, we can select data based on boolean masks:

In [ ]:
df

Name Language  Courses
0      Tom   Python        5
1     Mike   Python        4
2  Tiffany        R        7

In [ ]:
df[df['Courses'] > 5]

Name Language  Courses
2  Tiffany        R        7

In [ ]:
df[df['Name'] == "Tom"]

Name Language  Courses
0  Tom   Python        5

#### Indexing with `.query()`
Boolean masks work fine, but I prefer to use the `.query()` method for selecting data. `df.query()` is a powerful tool for filtering data. It has an odd syntax, one of the strangest I've seen in Python, it is more like SQL - `df.query()` accepts a string expression to evaluate and it "knows" the names of the columns in your dataframe.

In [ ]:
df.query("Courses > 4 & Language == 'Python'")

Name Language  Courses
0  Tom   Python        5

Note the use of single quotes AND double quotes above, lucky we have both in Python! Compare this to the equivalent boolean indexing operation and you can see that `.query()` is much more readable, especially as the query gets bigger!

In [ ]:
df[(df['Courses'] > 4) & (df['Language'] == 'Python')]

Name Language  Courses
0  Tom   Python        5

Query also allows you to reference variable in the current workspace using the `@` symbol:

In [ ]:
course_threshold = 4
df.query("Courses > @course_threshold")

Name Language  Courses
0      Tom   Python        5
2  Tiffany        R        7

#### Indexing cheatsheet

|Method|Syntax|Output|
|---|---|---|
|Select column|`df[col_label]`|Series|
|Select row slice|`df[row_1_int:row_2_int]`|DataFrame|
|Select row/column by label|`df.loc[row_label(s), col_label(s)]`|Object for single selection, Series for one row/column, otherwise DataFrame|
|Select row/column by integer|`df.iloc[row_int(s), col_int(s)]`|Object for single selection, Series for one row/column, otherwise DataFrame|
|Select by row integer & column label|`df.loc[df.index[row_int], col_label]`|Object for single selection, Series for one row/column, otherwise DataFrame|
|Select by row label & column integer|`df.loc[row_label, df.columns[col_int]]`|Object for single selection, Series for one row/column, otherwise DataFrame|
|Select by boolean|`df[bool_vec]`|Object for single selection, Series for one row/column, otherwise DataFrame|
|Select by boolean expression|`df.query("expression")`|Object for single selection, Series for one row/column, otherwise DataFrame|

### Reading/Writing Data From External Sources

#### .csv files

A lot of the time you will be loading .csv files for use in pandas. You can use the `pd.read_csv()` function for this. In the following chapters we'll use a real dataset of my cycling commutes to the University of British Columbia. There are so many arguments that can be used to help read in your .csv file in an efficient and appropriate manner, feel free to check them out now (by using `shift + tab` in Jupyter, or typing `help(pd.read_csv)`).

In [ ]:
path = 'data/cycling_data.csv'
df = pd.read_csv(path, index_col=0, parse_dates=True)
df

Name  Type   Time  Distance  \
Date                                                         
2019-09-10 00:13:04  Afternoon Ride  Ride   2084     12.62   
2019-09-10 13:52:18    Morning Ride  Ride   2531     13.03   
2019-09-11 00:23:50  Afternoon Ride  Ride   1863     12.52   
2019-09-11 14:06:19    Morning Ride  Ride   2192     12.84   
2019-09-12 00:28:05  Afternoon Ride  Ride   1891     12.48   
2019-09-16 13:57:48    Morning Ride  Ride   2272     12.45   
2019-09-17 00:15:47  Afternoon Ride  Ride   1973     12.45   
2019-09-17 13:43:34    Morning Ride  Ride   2285     12.60   
2019-09-18 13:49:53    Morning Ride  Ride   2903     14.57   
2019-09-18 00:15:52  Afternoon Ride  Ride   2101     12.48   
2019-09-19 00:30:01  Afternoon Ride  Ride  48062     12.48   
2019-09-19 13:52:09    Morning Ride  Ride   2090     12.59   
2019-09-20 01:02:05  Afternoon Ride  Ride   2961     12.81   
2019-09-23 13:50:41    Morning Ride  Ride   2462     12.68   
2019-09-24 00:35:42  Afternoon Ride  Ride   2076     12.47   
2019-09-24 13:41:24    Morning Ride  Ride   2321     12.68   
2019-09-25 00:07:21  Afternoon Ride  Ride   1775     12.10   
2019-09-25 13:35:41    Morning Ride  Ride   2124     12.65   
2019-09-26 00:13:33  Afternoon Ride  Ride   1860     12.52   
2019-09-26 13:42:43    Morning Ride  Ride   2350     12.91   
2019-09-27 01:00:18  Afternoon Ride  Ride   1712     12.47   
2019-09-30 13:53:52    Morning Ride  Ride   2118     12.71   
2019-10-01 00:15:07  Afternoon Ride  Ride   1732       NaN   
2019-10-01 13:45:55    Morning Ride  Ride   2222     12.82   
2019-10-02 00:13:09  Afternoon Ride  Ride   1756       NaN   
2019-10-02 13:46:06    Morning Ride  Ride   2134     13.06   
2019-10-03 00:45:22  Afternoon Ride  Ride   1724     12.52   
2019-10-03 13:47:36    Morning Ride  Ride   2182     12.68   
2019-10-04 01:08:08  Afternoon Ride  Ride   1870     12.63   
2019-10-09 13:55:40    Morning Ride  Ride   2149     12.70   
2019-10-10 00:10:31  Afternoon Ride  Ride   1841     12.59   
2019-10-10 13:47:14    Morning Ride  Ride   2463     12.79   
2019-10-11 00:16:57  Afternoon Ride  Ride   1843     11.79   

                                                      Comments  
Date                                                            
2019-09-10 00:13:04                                       Rain  
2019-09-10 13:52:18                                       rain  
2019-09-11 00:23:50                  Wet road but nice weather  
2019-09-11 14:06:19               Stopped for photo of sunrise  
2019-09-12 00:28:05               Tired by the end of the week  
2019-09-16 13:57:48                  Rested after the weekend!  
2019-09-17 00:15:47                       Legs feeling strong!  
2019-09-17 13:43:34                                    Raining  
2019-09-18 13:49:53                              Raining today  
2019-09-18 00:15:52                            Pumped up tires  
2019-09-19 00:30:01                               Feeling good  
2019-09-19 13:52:09               Getting colder which is nice  
2019-09-20 01:02:05                               Feeling good  
2019-09-23 13:50:41                  Rested after the weekend!  
2019-09-24 00:35:42             Oiled chain, bike feels smooth  
2019-09-24 13:41:24                 Bike feeling much smoother  
2019-09-25 00:07:21                       Feeling really tired  
2019-09-25 13:35:41               Stopped for photo of sunrise  
2019-09-26 00:13:33                                    raining  
2019-09-26 13:42:43            Detour around trucks at Jericho  
2019-09-27 01:00:18               Tired by the end of the week  
2019-09-30 13:53:52                  Rested after the weekend!  
2019-10-01 00:15:07                       Legs feeling strong!  
2019-10-01 13:45:55             Beautiful morning! Feeling fit  
2019-10-02 00:13:09      A little tired today but good weather  
2019-10-02 13:46:06           Bit tired today but good weather  
2019-10-03 00:45:22                     

You can print a dataframe to .csv using `df.to_csv()`. Be sure to check out all of the possible arguments to write your dataframe exactly how you want it.

#### url

Pandas also facilitates reading directly from a url - `pd.read_csv()` accepts urls as input:

In [ ]:
url = 'https://raw.githubusercontent.com/TomasBeuzen/toy-datasets/master/wine_1.csv'
pd.read_csv(url)

Bottle         Grape     Origin  Alcohol    pH Colour   Aroma
0       1    Chardonnay  Australia    14.23  3.51  White  Floral
1       2  Pinot Grigio      Italy    13.20  3.30  White  Fruity
2       3   Pinot Blanc     France    13.16  3.16  White  Citrus
3       4        Shiraz      Chile    14.91  3.39    Red   Berry
4       5        Malbec  Argentina    13.83  3.28    Red  Fruity

#### Other
Pandas can read data from all sorts of other file types including HTML, JSON, Excel, Parquet, Feather, etc. There are generally dedicated functions for reading these file types, see the [Pandas documentation here](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-tools-text-csv-hdf5).

### Common DataFrame Operations

DataFrames have built-in functions for performing most common operations, e.g., `.min()`, `idxmin()`, `sort_values()`, etc. They're all documented in the [Pandas documentation here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html) but I'll demonstrate a few below:

In [ ]:
df = pd.read_csv('data/cycling_data.csv')
df

Date            Name  Type   Time  Distance  \
0   10 Sep 2019, 00:13:04  Afternoon Ride  Ride   2084     12.62   
1   10 Sep 2019, 13:52:18    Morning Ride  Ride   2531     13.03   
2   11 Sep 2019, 00:23:50  Afternoon Ride  Ride   1863     12.52   
3   11 Sep 2019, 14:06:19    Morning Ride  Ride   2192     12.84   
4   12 Sep 2019, 00:28:05  Afternoon Ride  Ride   1891     12.48   
5   16 Sep 2019, 13:57:48    Morning Ride  Ride   2272     12.45   
6   17 Sep 2019, 00:15:47  Afternoon Ride  Ride   1973     12.45   
7   17 Sep 2019, 13:43:34    Morning Ride  Ride   2285     12.60   
8   18 Sep 2019, 13:49:53    Morning Ride  Ride   2903     14.57   
9   18 Sep 2019, 00:15:52  Afternoon Ride  Ride   2101     12.48   
10  19 Sep 2019, 00:30:01  Afternoon Ride  Ride  48062     12.48   
11  19 Sep 2019, 13:52:09    Morning Ride  Ride   2090     12.59   
12  20 Sep 2019, 01:02:05  Afternoon Ride  Ride   2961     12.81   
13  23 Sep 2019, 13:50:41    Morning Ride  Ride   2462     12.68   
14  24 Sep 2019, 00:35:42  Afternoon Ride  Ride   2076     12.47   
15  24 Sep 2019, 13:41:24    Morning Ride  Ride   2321     12.68   
16  25 Sep 2019, 00:07:21  Afternoon Ride  Ride   1775     12.10   
17  25 Sep 2019, 13:35:41    Morning Ride  Ride   2124     12.65   
18  26 Sep 2019, 00:13:33  Afternoon Ride  Ride   1860     12.52   
19  26 Sep 2019, 13:42:43    Morning Ride  Ride   2350     12.91   
20  27 Sep 2019, 01:00:18  Afternoon Ride  Ride   1712     12.47   
21  30 Sep 2019, 13:53:52    Morning Ride  Ride   2118     12.71   
22   1 Oct 2019, 00:15:07  Afternoon Ride  Ride   1732       NaN   
23   1 Oct 2019, 13:45:55    Morning Ride  Ride   2222     12.82   
24   2 Oct 2019, 00:13:09  Afternoon Ride  Ride   1756       NaN   
25   2 Oct 2019, 13:46:06    Morning Ride  Ride   2134     13.06   
26   3 Oct 2019, 00:45:22  Afternoon Ride  Ride   1724     12.52   
27   3 Oct 2019, 13:47:36    Morning Ride  Ride   2182     12.68   
28   4 Oct 2019, 01:08:08  Afternoon Ride  Ride   1870     12.63   
29   9 Oct 2019, 13:55:40    Morning Ride  Ride   2149     12.70   
30  10 Oct 2019, 00:10:31  Afternoon Ride  Ride   1841     12.59   
31  10 Oct 2019, 13:47:14    Morning Ride  Ride   2463     12.79   
32  11 Oct 2019, 00:16:57  Afternoon Ride  Ride   1843     11.79   

                                     Comments  
0                                        Rain  
1                                        rain  
2                   Wet road but nice weather  
3                Stopped for photo of sunrise  
4                Tired by the end of the week  
5                   Rested after the weekend!  
6                        Legs feeling strong!  
7                                     Raining  
8                               Raining today  
9                             Pumped up tires  
10                               Feeling good  
11               Getting colder which is nice  
12                               Feeling good  
13                  Rested after the weekend!  
14             Oiled chain, bike feels smooth  
15                 Bike feeling much smoother  
16                       Feeling really tired  
17               Stopped for photo of sunrise  
18                                    raining  
19            Detour around trucks at Jericho  
20               Tired by the end of the week  
21                  Rested after the weekend!  
22                       Legs feeling strong!  
23             Beautiful morning! Feeling fit  
24      A little tired today but good weather  
25           Bit tired today but good weather  
26                               Feeling good  
27                                   Wet road  
28           Very tired, riding into the wind  
29              Really cold! But feeling good  
30        Feeling good after a holiday break!  
31               Stopped for photo of sunrise  
32  Bike feeling tight, needs an oil and pump

In [ ]:
df.min()

Date                         1 Oct 2019, 00:15:07
Name                               Afternoon Ride
Type                                         Ride
Time                                         1712
Distance                                    11.79
Comments    A little tired today but good weather
dtype: object

In [ ]:
df['Time'].min()

1712

In [ ]:
df['Time'].idxmin()

20

In [ ]:
df.iloc[20]

Date               27 Sep 2019, 01:00:18
Name                      Afternoon Ride
Type                                Ride
Time                                1712
Distance                           12.47
Comments    Tired by the end of the week
Name: 20, dtype: object

In [ ]:
df.sum()

Date        10 Sep 2019, 00:13:0410 Sep 2019, 13:52:1811 S...
Name        Afternoon RideMorning RideAfternoon RideMornin...
Type        RideRideRideRideRideRideRideRideRideRideRideRi...
Time                                                   115922
Distance                                               392.69
Comments    RainrainWet road but nice weatherStopped for p...
dtype: object

Some methods like `.mean()` will only operate on numeric columns:

In [ ]:
df.mean()

Time        3512.787879
Distance      12.667419
dtype: float64

Some methods require arguments to be specified, like `.sort_values()`:

In [ ]:
df.sort_values(by='Time')

Date            Name  Type   Time  Distance  \
20  27 Sep 2019, 01:00:18  Afternoon Ride  Ride   1712     12.47   
26   3 Oct 2019, 00:45:22  Afternoon Ride  Ride   1724     12.52   
22   1 Oct 2019, 00:15:07  Afternoon Ride  Ride   1732       NaN   
24   2 Oct 2019, 00:13:09  Afternoon Ride  Ride   1756       NaN   
16  25 Sep 2019, 00:07:21  Afternoon Ride  Ride   1775     12.10   
30  10 Oct 2019, 00:10:31  Afternoon Ride  Ride   1841     12.59   
32  11 Oct 2019, 00:16:57  Afternoon Ride  Ride   1843     11.79   
18  26 Sep 2019, 00:13:33  Afternoon Ride  Ride   1860     12.52   
2   11 Sep 2019, 00:23:50  Afternoon Ride  Ride   1863     12.52   
28   4 Oct 2019, 01:08:08  Afternoon Ride  Ride   1870     12.63   
4   12 Sep 2019, 00:28:05  Afternoon Ride  Ride   1891     12.48   
6   17 Sep 2019, 00:15:47  Afternoon Ride  Ride   1973     12.45   
14  24 Sep 2019, 00:35:42  Afternoon Ride  Ride   2076     12.47   
0   10 Sep 2019, 00:13:04  Afternoon Ride  Ride   2084     12.62   
11  19 Sep 2019, 13:52:09    Morning Ride  Ride   2090     12.59   
9   18 Sep 2019, 00:15:52  Afternoon Ride  Ride   2101     12.48   
21  30 Sep 2019, 13:53:52    Morning Ride  Ride   2118     12.71   
17  25 Sep 2019, 13:35:41    Morning Ride  Ride   2124     12.65   
25   2 Oct 2019, 13:46:06    Morning Ride  Ride   2134     13.06   
29   9 Oct 2019, 13:55:40    Morning Ride  Ride   2149     12.70   
27   3 Oct 2019, 13:47:36    Morning Ride  Ride   2182     12.68   
3   11 Sep 2019, 14:06:19    Morning Ride  Ride   2192     12.84   
23   1 Oct 2019, 13:45:55    Morning Ride  Ride   2222     12.82   
5   16 Sep 2019, 13:57:48    Morning Ride  Ride   2272     12.45   
7   17 Sep 2019, 13:43:34    Morning Ride  Ride   2285     12.60   
15  24 Sep 2019, 13:41:24    Morning Ride  Ride   2321     12.68   
19  26 Sep 2019, 13:42:43    Morning Ride  Ride   2350     12.91   
13  23 Sep 2019, 13:50:41    Morning Ride  Ride   2462     12.68   
31  10 Oct 2019, 13:47:14    Morning Ride  Ride   2463     12.79   
1   10 Sep 2019, 13:52:18    Morning Ride  Ride   2531     13.03   
8   18 Sep 2019, 13:49:53    Morning Ride  Ride   2903     14.57   
12  20 Sep 2019, 01:02:05  Afternoon Ride  Ride   2961     12.81   
10  19 Sep 2019, 00:30:01  Afternoon Ride  Ride  48062     12.48   

                                     Comments  
20               Tired by the end of the week  
26                               Feeling good  
22                       Legs feeling strong!  
24      A little tired today but good weather  
16                       Feeling really tired  
30        Feeling good after a holiday break!  
32  Bike feeling tight, needs an oil and pump  
18                                    raining  
2                   Wet road but nice weather  
28           Very tired, riding into the wind  
4                Tired by the end of the week  
6                        Legs feeling strong!  
14             Oiled chain, bike feels smooth  
0                                        Rain  
11               Getting colder which is nice  
9                             Pumped up tires  
21                  Rested after the weekend!  
17               Stopped for photo of sunrise  
25           Bit tired today but good weather  
29              Really cold! But feeling good  
27                                   Wet road  
3                Stopped for photo of sunrise  
23             Beautiful morning! Feeling fit  
5                   Rested after the weekend!  
7                                     Raining  
15                 Bike feeling much smoother  
19            Detour around trucks at Jericho  
13                  Rested after the weekend!  
31               Stopped for photo of sunrise  
1                                        rain  
8                               Raining today  
12                               Feeling good  
10                               Feeling good

In [ ]:
df.sort_values(by='Time', ascending=False)

Date            Name  Type   Time  Distance  \
10  19 Sep 2019, 00:30:01  Afternoon Ride  Ride  48062     12.48   
12  20 Sep 2019, 01:02:05  Afternoon Ride  Ride   2961     12.81   
8   18 Sep 2019, 13:49:53    Morning Ride  Ride   2903     14.57   
1   10 Sep 2019, 13:52:18    Morning Ride  Ride   2531     13.03   
31  10 Oct 2019, 13:47:14    Morning Ride  Ride   2463     12.79   
13  23 Sep 2019, 13:50:41    Morning Ride  Ride   2462     12.68   
19  26 Sep 2019, 13:42:43    Morning Ride  Ride   2350     12.91   
15  24 Sep 2019, 13:41:24    Morning Ride  Ride   2321     12.68   
7   17 Sep 2019, 13:43:34    Morning Ride  Ride   2285     12.60   
5   16 Sep 2019, 13:57:48    Morning Ride  Ride   2272     12.45   
23   1 Oct 2019, 13:45:55    Morning Ride  Ride   2222     12.82   
3   11 Sep 2019, 14:06:19    Morning Ride  Ride   2192     12.84   
27   3 Oct 2019, 13:47:36    Morning Ride  Ride   2182     12.68   
29   9 Oct 2019, 13:55:40    Morning Ride  Ride   2149     12.70   
25   2 Oct 2019, 13:46:06    Morning Ride  Ride   2134     13.06   
17  25 Sep 2019, 13:35:41    Morning Ride  Ride   2124     12.65   
21  30 Sep 2019, 13:53:52    Morning Ride  Ride   2118     12.71   
9   18 Sep 2019, 00:15:52  Afternoon Ride  Ride   2101     12.48   
11  19 Sep 2019, 13:52:09    Morning Ride  Ride   2090     12.59   
0   10 Sep 2019, 00:13:04  Afternoon Ride  Ride   2084     12.62   
14  24 Sep 2019, 00:35:42  Afternoon Ride  Ride   2076     12.47   
6   17 Sep 2019, 00:15:47  Afternoon Ride  Ride   1973     12.45   
4   12 Sep 2019, 00:28:05  Afternoon Ride  Ride   1891     12.48   
28   4 Oct 2019, 01:08:08  Afternoon Ride  Ride   1870     12.63   
2   11 Sep 2019, 00:23:50  Afternoon Ride  Ride   1863     12.52   
18  26 Sep 2019, 00:13:33  Afternoon Ride  Ride   1860     12.52   
32  11 Oct 2019, 00:16:57  Afternoon Ride  Ride   1843     11.79   
30  10 Oct 2019, 00:10:31  Afternoon Ride  Ride   1841     12.59   
16  25 Sep 2019, 00:07:21  Afternoon Ride  Ride   1775     12.10   
24   2 Oct 2019, 00:13:09  Afternoon Ride  Ride   1756       NaN   
22   1 Oct 2019, 00:15:07  Afternoon Ride  Ride   1732       NaN   
26   3 Oct 2019, 00:45:22  Afternoon Ride  Ride   1724     12.52   
20  27 Sep 2019, 01:00:18  Afternoon Ride  Ride   1712     12.47   

                                     Comments  
10                               Feeling good  
12                               Feeling good  
8                               Raining today  
1                                        rain  
31               Stopped for photo of sunrise  
13                  Rested after the weekend!  
19            Detour around trucks at Jericho  
15                 Bike feeling much smoother  
7                                     Raining  
5                   Rested after the weekend!  
23             Beautiful morning! Feeling fit  
3                Stopped for photo of sunrise  
27                                   Wet road  
29              Really cold! But feeling good  
25           Bit tired today but good weather  
17               Stopped for photo of sunrise  
21                  Rested after the weekend!  
9                             Pumped up tires  
11               Getting colder which is nice  
0                                        Rain  
14             Oiled chain, bike feels smooth  
6                        Legs feeling strong!  
4                Tired by the end of the week  
28           Very tired, riding into the wind  
2                   Wet road but nice weather  
18                                    raining  
32  Bike feeling tight, needs an oil and pump  
30        Feeling good after a holiday break!  
16                       Feeling really tired  
24      A little tired today but good weather  
22                       Legs feeling strong!  
26                               Feeling good  
20               Tired by the end of the week

Some methods will operate on the index/columns, like `.sort_index()`:

In [ ]:
df.sort_index(ascending=False)

Date            Name  Type   Time  Distance  \
32  11 Oct 2019, 00:16:57  Afternoon Ride  Ride   1843     11.79   
31  10 Oct 2019, 13:47:14    Morning Ride  Ride   2463     12.79   
30  10 Oct 2019, 00:10:31  Afternoon Ride  Ride   1841     12.59   
29   9 Oct 2019, 13:55:40    Morning Ride  Ride   2149     12.70   
28   4 Oct 2019, 01:08:08  Afternoon Ride  Ride   1870     12.63   
27   3 Oct 2019, 13:47:36    Morning Ride  Ride   2182     12.68   
26   3 Oct 2019, 00:45:22  Afternoon Ride  Ride   1724     12.52   
25   2 Oct 2019, 13:46:06    Morning Ride  Ride   2134     13.06   
24   2 Oct 2019, 00:13:09  Afternoon Ride  Ride   1756       NaN   
23   1 Oct 2019, 13:45:55    Morning Ride  Ride   2222     12.82   
22   1 Oct 2019, 00:15:07  Afternoon Ride  Ride   1732       NaN   
21  30 Sep 2019, 13:53:52    Morning Ride  Ride   2118     12.71   
20  27 Sep 2019, 01:00:18  Afternoon Ride  Ride   1712     12.47   
19  26 Sep 2019, 13:42:43    Morning Ride  Ride   2350     12.91   
18  26 Sep 2019, 00:13:33  Afternoon Ride  Ride   1860     12.52   
17  25 Sep 2019, 13:35:41    Morning Ride  Ride   2124     12.65   
16  25 Sep 2019, 00:07:21  Afternoon Ride  Ride   1775     12.10   
15  24 Sep 2019, 13:41:24    Morning Ride  Ride   2321     12.68   
14  24 Sep 2019, 00:35:42  Afternoon Ride  Ride   2076     12.47   
13  23 Sep 2019, 13:50:41    Morning Ride  Ride   2462     12.68   
12  20 Sep 2019, 01:02:05  Afternoon Ride  Ride   2961     12.81   
11  19 Sep 2019, 13:52:09    Morning Ride  Ride   2090     12.59   
10  19 Sep 2019, 00:30:01  Afternoon Ride  Ride  48062     12.48   
9   18 Sep 2019, 00:15:52  Afternoon Ride  Ride   2101     12.48   
8   18 Sep 2019, 13:49:53    Morning Ride  Ride   2903     14.57   
7   17 Sep 2019, 13:43:34    Morning Ride  Ride   2285     12.60   
6   17 Sep 2019, 00:15:47  Afternoon Ride  Ride   1973     12.45   
5   16 Sep 2019, 13:57:48    Morning Ride  Ride   2272     12.45   
4   12 Sep 2019, 00:28:05  Afternoon Ride  Ride   1891     12.48   
3   11 Sep 2019, 14:06:19    Morning Ride  Ride   2192     12.84   
2   11 Sep 2019, 00:23:50  Afternoon Ride  Ride   1863     12.52   
1   10 Sep 2019, 13:52:18    Morning Ride  Ride   2531     13.03   
0   10 Sep 2019, 00:13:04  Afternoon Ride  Ride   2084     12.62   

                                     Comments  
32  Bike feeling tight, needs an oil and pump  
31               Stopped for photo of sunrise  
30        Feeling good after a holiday break!  
29              Really cold! But feeling good  
28           Very tired, riding into the wind  
27                                   Wet road  
26                               Feeling good  
25           Bit tired today but good weather  
24      A little tired today but good weather  
23             Beautiful morning! Feeling fit  
22                       Legs feeling strong!  
21                  Rested after the weekend!  
20               Tired by the end of the week  
19            Detour around trucks at Jericho  
18                                    raining  
17               Stopped for photo of sunrise  
16                       Feeling really tired  
15                 Bike feeling much smoother  
14             Oiled chain, bike feels smooth  
13                  Rested after the weekend!  
12                               Feeling good  
11               Getting colder which is nice  
10                               Feeling good  
9                             Pumped up tires  
8                               Raining today  
7                                     Raining  
6                        Legs feeling strong!  
5                   Rested after the weekend!  
4                Tired by the end of the week  
3                Stopped for photo of sunrise  
2                   Wet road but nice weather  
1                                        rain  
0                                        Rain

## 10. Why ndarrays and Series and DataFrames?

At this point, you might be asking why we need all these different data structures. Well, they all serve different purposes and are suited to different tasks. For example:
- NumPy is typically faster/uses less memory than Pandas;
- not all Python packages are compatible with NumPy & Pandas;
- the ability to add labels to data can be useful (e.g., for time series);
- NumPy and Pandas have different built-in functions available.

My advice: use the simplest data structure that fulfills your needs!

Finally, we've seen how to go from: ndarray (`np.array()`) -> series (`pd.series()`) -> dataframe (`pd.DataFrame()`). Remember that we can also go the other way: dataframe/series -> ndarray using `df.to_numpy()`.